# -*- coding: utf-8 -*-
"""GrowthFlow Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jtmx2_BAWWgR4dKXdAYK_qcGTqaRSwBm
"""

# Data upload and setup

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

@st.cache_data
def load_all_data():
    customers_df = pd.read_csv('gfcustomer_information.csv')
    status_df = pd.read_csv('gfmonthly_status.csv')
    usage_df = pd.read_csv('gfusage_data.csv')
    feedback_df = pd.read_csv('gffeedback_data.csv')
    engagement_df = pd.read_csv('gfengagement_data.csv')
    
    model_df = customers_df.merge(status_df, on='customer_id', how='inner') \
                           .merge(usage_df, on='customer_id', how='inner') \
                           .merge(feedback_df, on='customer_id', how='inner') \
                           .merge(engagement_df, on='customer_id', how='inner')
                           
    return customers_df, status_df, usage_df, feedback_df, engagement_df, model_df

# Unpack everything so 'customers_df', 'status_df', etc. exist for line 41
customers_df, status_df, usage_df, feedback_df, engagement_df, model_df = load_all_data()


# Dataset Overview
dfs = {
    'Customers': customers_df,
    'Status': status_df,
    'Usage': usage_df,
    'Feedback': feedback_df,
    'Engagement': engagement_df
}

st.subheader("Datasets Overview")

# Display Table Info & Previews in clean, expandable sections
for name, df in dfs.items():
    with st.expander(f"=== {name} Table ({df.shape[0]:,} rows, {df.shape[1]} cols) ==="):
        st.write("**Columns:**", list(df.columns))
        st.write("**Preview:**")
        st.dataframe(df.head(3))

"""# Data Cleaning"""

@st.cache_data
def load_and_clean_data():
    # 1. Load Data
    customers_df = pd.read_csv('gfcustomer_information.csv')
    status_df = pd.read_csv('gfmonthly_status.csv')
    usage_df = pd.read_csv('gfusage_data.csv')
    feedback_df = pd.read_csv('gffeedback_data.csv')
    engagement_df = pd.read_csv('gfengagement_data.csv')

    # 2. Convert Date Columns
    customers_df['subscription_date'] = pd.to_datetime(customers_df['subscription_date'])
    status_df['activity_month'] = pd.to_datetime(status_df['activity_month'])
    usage_df['activity_month'] = pd.to_datetime(usage_df['activity_month'])
    feedback_df['feedback_month'] = pd.to_datetime(feedback_df['feedback_month'])
    engagement_df['engagement_month'] = pd.to_datetime(engagement_df['engagement_month'])

    return customers_df, status_df, usage_df, feedback_df, engagement_df

# Load cached data
customers_df, status_df, usage_df, feedback_df, engagement_df = load_and_clean_data()

# Optional: Display Referential Integrity Check on Dashboard
with st.expander("🔍 Referential Integrity Check"):
    master_ids = set(customers_df['customer_id'])
    dfs_to_check = {
        'Status': status_df,
        'Usage': usage_df,
        'Feedback': feedback_df,
        'Engagement': engagement_df
    }
    
    for name, df in dfs_to_check.items():
        table_ids = set(df['customer_id'])
        unmatched = table_ids - master_ids
        if len(unmatched) == 0:
            st.success(f"**{name}:** All {len(table_ids):,} unique customers exist in master Customers table.")
        else:
            st.warning(f"**{name}:** Found {len(unmatched)} IDs not present in master Customers table.")

# Check for duplicate customer IDs in the primary dimension table
duplicates = customers_df[customers_df.duplicated(subset=['customer_id'], keep=False)]
num_duplicates = duplicates['customer_id'].nunique()

# Inspect unique values in categorical columns
unique_customer_types = customers_df[['customer_type']].drop_duplicates()

# Optional: Display checks in an expander on your dashboard
with st.expander("🔎 Data Quality Checks"):
    if num_duplicates == 0:
        st.success("✓ Duplicate Customer IDs found: **0**")
    else:
        st.warning(f"⚠️ Duplicate Customer IDs found: **{num_duplicates}**")
        st.dataframe(duplicates)

    st.write("**Unique Customer Types:**")
    st.dataframe(unique_customer_types)
    
"""# EDA

**Numerical Columns Audit**

**Objective**
Scan all the number-based columns across our database tables (such as company size, monthly revenue, session duration, and satisfaction scores) to check for missing values, average numbers, price ranges, and unusual extremes.
This gives us a clear look at the mathematical health and distribution of our numbers before building advanced statistical models.

**Technical Approach**
Found All Number Columns: Programmatically scanned through every table to pull out purely numerical features.
Calculated Key Summary Stats: For every numeric column, we derived:
Completeness: Checked for missing or empty numbers.
Average vs. Middle (Mean vs. Median): Compared the average value to the middle value to see if extreme outliers were pulling the numbers up or down.
Spread & Ranges (Min & Max): Tracked the lowest and highest values to verify boundary conditions.
Skewness: Measured whether the data was evenly spread out or heavily lopsided toward smaller/larger values.
Consolidated Findings: Combined all numeric metrics into a single reference report.

**Key Results & Insights**
100% Data Completeness:
Zero missing values (missing_count = 0) across every numeric feature in all five tables, confirming strong numerical integrity.
Company Size Distribution:
Lopsided Toward Small Businesses: While the average company size is 498 employees, the median is just 41 employees (ranging from 1 to 4,998). A few massive enterprise clients pull the average up, but most customers are smaller operations.
Revenue & Tenure Baseline:
Tenure: Average customer tenure across active monthly records is 7 months (ranging from 0 to 23 months).
Monthly Revenue: Average revenue per monthly record is $205.37 (ranging from $29.00 to $999.00).
Product Usage Trends:
Session Length: Users average 34.75 minutes per session (median: 30 minutes).
Feature Popularity: Core features like CRM (1.08 uses/mo) and Email Campaigns (0.77 uses/mo) see steady usage. Advanced tools like Custom Workflows (0.05 uses/mo) and Advanced Analytics (0.16 uses/mo) have much lower adoption and are used primarily by power users.
Customer Sentiment & Feedback:
Satisfaction: Customers rate us well, with a balanced average Satisfaction Score of 7.20 / 10 (median: 7.00).
NPS Score: Net Promoter Score averages +21.94 (ranging from -33 to +73), showing generally positive customer sentiment.
Campaign Engagement:
Response Rate: Customers respond to campaigns an average of 53% of the time (0.53 rate).

**Business Takeaway**
Our numerical data is clean, complete, and reliable. The metrics confirm that our typical user is a small business (around 40 employees) spending about $200/month and spending 30 minutes per session on core tools like CRM and email. There is a huge opportunity to drive adoption for underutilized advanced tools to help push clients into higher pricing tiers.
"""

# Descriptive stats for numerical columns across all 5 tables

# Define your dictionary of DataFrames
dfs = {
    'gfcustomer_information': customers_df,
    'gfmonthly_status': status_df,
    'gfusage_data': usage_df,
    'gffeedback_data': feedback_df,
    'gfengagement_data': engagement_df
}

num_summaries = []

for table_name, df in dfs.items():
    # Select numeric columns only
    numeric_df = df.select_dtypes(include=[np.number])

    for col in numeric_df.columns:
        num_summaries.append({
            'table_name': table_name,
            'column_name': col,
            'count': numeric_df[col].count(),
            'missing_count': numeric_df[col].isnull().sum(),
            'mean': round(numeric_df[col].mean(), 2),
            'std': round(numeric_df[col].std(), 2),
            'min': round(numeric_df[col].min(), 2),
            'median': round(numeric_df[col].median(), 2),
            'max': round(numeric_df[col].max(), 2),
            'skewness': round(numeric_df[col].skew(), 2)
        })

# Combine into a single consolidated summary DataFrame
df_numerical_summary = pd.DataFrame(num_summaries)

# Display in Streamlit
st.subheader("🔢 Consolidated Numerical Summary")
st.dataframe(df_numerical_summary, use_container_width=True)


"""**Categorical Columns Audit**

**Objective**
Scan all non-numeric text columns across our 5 database tables (like customer type, plan tier, region, and industry) to check for data quality, count unique categories, and find the most common values.
Think of this as a health check on our text data to ensure there are no missing details or weird entries before running deeper analytics.

**Technical Approach**
Found All Text Columns: Automatically searched through every table to pull out text fields (categories, names, dates, and types).
Ran Quality & Frequency Checks: For every column, we checked:
Completeness: Are there any missing or blank values?
Variety (Cardinality): How many unique choices exist (e.g., 3 customer types, 4 regions)?
Most Common Value (Mode): Which single option appears the most, and what percentage of the total does it make up?
Combined into One Master Summary Table: Consolidated all stats into a single report for easy auditing.

**Key Results & Insights**
100% Data Completeness (Zero Missing Data):
There are 0 missing values across every text column in all 5 tables. The data is extremely clean and ready for modeling.
Customer Profile Highlights (5,000 Accounts):
Main Customer Segment: SMBs (Small-to-Medium Businesses) make up 60.24% of our total customer base (3,012 accounts).
Popular Plan: Basic tier is the most common subscription, representing 53.16% of subscribers (2,658 accounts).
Primary Region: North America is our largest geographic market at 39.52% (1,976 accounts).
Industry Breakdown: Retail is the single largest industry at 17.26% (863 accounts), though customers are well-balanced across 6 different sectors.
Activity & Engagement Logs:
Monthly Status (54,021 records): Peak monthly activity occurred in November 2025 (3,873 active records).
Feedback Logs (1,447 records): Product-related issues/feedback was the top category, making up 44.30% of all customer feedback.
Engagement Logs (14,532 records): Interaction logs peaked in December 2025 (1,223 engagement events).

**Business Takeaway**
Our data hygiene is in excellent shape with zero missing values, meaning we don't need to throw out records or fill in blanks. Our core customer identity is clear: we primarily serve North American SMBs on Basic plans, with Product Feedback being the main reason customers reach out to us.
"""

# Descriptive stats for categorical columns across all 5 tables

# 1. Consolidated Categorical Summary
dfs = {
    'gfcustomer_information': customers_df,
    'gfmonthly_status': status_df,
    'gfusage_data': usage_df,
    'gffeedback_data': feedback_df,
    'gfengagement_data': engagement_df
}

cat_summaries = []

for table_name, df in dfs.items():
    # Select non-numeric / string columns
    categorical_df = df.select_dtypes(include=['object', 'category'])

    for col in categorical_df.columns:
        total_rows = len(categorical_df)
        mode_series = categorical_df[col].mode()
        top_val = mode_series.iloc[0] if not mode_series.empty else None
        top_freq = categorical_df[col].value_counts().iloc[0] if not categorical_df[col].empty else 0

        cat_summaries.append({
            'table_name': table_name,
            'column_name': col,
            'total_rows': total_rows,
            'unique_values': categorical_df[col].nunique(),
            'missing_count': categorical_df[col].isnull().sum(),
            'most_frequent_value': top_val,
            'top_value_count': top_freq,
            'top_value_pct': round((top_freq / total_rows) * 100, 2) if total_rows > 0 else 0
        })

df_categorical_summary = pd.DataFrame(cat_summaries)

# Render Categorical Table in Streamlit
st.subheader("🔤 Consolidated Categorical Summary")
st.dataframe(df_categorical_summary, use_container_width=True)

# 2. Timeframe Analysis
start_date = status_df['activity_month'].min()
end_date = status_df['activity_month'].max()

# Ensure activity_month is datetime type to calculate distinct months accurately
if not pd.api.types.is_datetime64_any_dtype(status_df['activity_month']):
    status_dt = pd.to_datetime(status_df['activity_month'])
else:
    status_dt = status_df['activity_month']

total_months = status_dt.dt.to_period('M').nunique()
years = total_months // 12
remaining_months = total_months % 12

# Format dates to YYYY-MM-DD string format
start_str = pd.to_datetime(start_date).strftime('%Y-%m-%d')
end_str = pd.to_datetime(end_date).strftime('%Y-%m-%d')

# Render Timeframe Info using Streamlit Metrics / Info Box
st.subheader("📅 Activity Timeframe")
st.info(
    f"**Timeframe:** {start_str} to {end_str}\n\n"
    f"**Duration:** {total_months} months ({years} years, {remaining_months} months)"
)

"""**High-Level Account Churn & Retention Baseline (SQL Query)**
**Objective**
Calculate our overall company-wide churn rate to set a baseline benchmark.
Instead of looking at specific subgroups or monthly trends, this query steps back to look at all 5,000 customers in our database and divides them into two simple groups: customers who stayed active versus customers who canceled up to our snapshot cutoff date (December 1, 2025).
**Technical Approach**
Found Each Customer's Last Active Month: Used a query to find the single most recent month every customer logged activity.
Flagged Active vs. Canceled Accounts:
Active: Customers whose last logged month was December 2025 (the latest month in our data).
Churned: Customers whose last logged month was before December 2025 (meaning they stopped using the product).
Calculated the Overall Retention Ratio: Derived total account counts and calculated the percentage of the overall customer base that churned versus remained active.

**Key Results & Insights**
Total Customer Base: 5,000 total accounts tracked across the dataset lifecycle.
Active Customer Retention: 3,366 active accounts (67.32% retention rate).
Total Customer Attrition: 1,634 churned accounts.
Overall Baseline Churn Rate: 32.68%.

**Business Takeaway**
32.68% is our company-wide benchmark.
This number gives us a clear standard to judge all other business segments against. Any customer tier, region, or plan with a churn rate higher than 32.68% (such as SMBs at 36.6% or Basic plans at 35.3%) represents an above-average risk zone where retention interventions will have the biggest impact.
"""

# Churn Rate

# 1. Step 1: Find the last recorded month for each customer
customer_last_month = status_df.groupby('customer_id')['activity_month'].max().reset_index()
customer_last_month.rename(columns={'activity_month': 'max_month'}, inplace=True)

# Determine the overall latest month in the dataset dynamically
latest_dataset_month = customer_last_month['max_month'].max()

# 2. Step 2: Calculate churn metrics
total_customers = len(customer_last_month)
total_churned = (customer_last_month['max_month'] < latest_dataset_month).sum()
total_active = (customer_last_month['max_month'] == latest_dataset_month).sum()
churn_rate_pct = round((total_churned / total_customers) * 100, 2) if total_customers > 0 else 0.0

# 3. Format as a clean DataFrame (matching your SQL output shape)
df_simple = pd.DataFrame([{
    'total_customers': total_customers,
    'total_churned': total_churned,
    'total_active': total_active,
    'churn_rate_pct': churn_rate_pct
}])

# Render in Streamlit
st.subheader("Churn Rate Overview")

# Option A: Display as Streamlit Metric KPI Cards (Recommended)
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Customers", f"{total_customers:,}")
col2.metric("Active Customers", f"{total_active:,}")
col3.metric("Churned Customers", f"{total_churned:,}")
col4.metric("Churn Rate", f"{churn_rate_pct}%")

# Option B: Display as standard table preview
st.dataframe(df_simple, use_container_width=True)

"""**Multi-Dimensional Churn & Volume Segmentation**
**Objective**
Evaluate customer distribution and attrition rates across key operational and demographic dimensions—Industry, Region, Customer Type, and Plan Type—to identify structural churn concentrations and risk profiles.
**Technical Approach**
Captured Final Customer Status: Looked at each customer's final recorded month to mark them as either retained or churned.
Calculated Key Group Metrics: For every category, we measured:
Total Customer Volume: The total number of unique customers in that group.
Churn Rate (%): The percentage of customers in that group who canceled.
Built Comparative Visuals: Created a side-by-side dashboard comparing customer volume directly against churn percentages across all four dimensions.

**Key Results & Insights**
Industry Sectors:
Volume: Customer volume is evenly split across industries (~800–830 customers each).
Churn: Education (34.4%) and Finance (34.3%) have the highest churn rates, while E-commerce (30.2%) is the most stable.
Geographic Regions:
Volume: Europe is our largest market (1,322 customers), followed by Asia-Pacific and Latin America.
Churn: Latin America has the highest cancellation rate (35.2%), while North America, Europe, and Asia-Pacific stay lower (31.2%–33.2%).
Company Size (Customer Type):
Volume: Small-to-Medium Businesses (SMBs) make up the majority of our customers.
Churn: Smaller companies leave at much higher rates. SMBs churn at 36.6%, Mid-Market at 28.9%, and Enterprise accounts at just 23.1%.
Plan Tier:
Volume: Pro and Basic plans hold the vast majority of subscribers.
Churn: Basic plans churn highest (35.3%), Pro at 30.5%, and Enterprise plans lowest (28.5%).

**Business Takeaway**
The data shows a clear pattern: Larger customers stay with us longer.
While smaller accounts (SMBs and Basic plans) churn at higher rates (35%–37%), larger clients (Enterprise) are much more sticky (23%–28% churn). We should focus on simplifying onboarding and initial support for SMBs to lower early drop-offs, while continuing to protect our stable, high-value Enterprise accounts.
"""

# Churn rate by Industy, region, cusomer type, plan type, trends in monthly subscription
# Set overall style
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 11})

st.subheader("Churn Analysis by Segment")

# ----------------------------------------------------
# 1. Prepare data and determine churn flag per customer
# ----------------------------------------------------
# Identify latest activity month across dataset
max_month = status_df['activity_month'].max()

# Last active month per customer
customer_last = status_df.groupby('customer_id')['activity_month'].max().reset_index()
customer_last['is_churned'] = (customer_last['activity_month'] < max_month).astype(int)

# Merge customer demographic attributes from customers_df with churn status
customer_profile = customers_df.merge(
    customer_last[['customer_id', 'is_churned']], 
    on='customer_id', 
    how='left'
)

# ----------------------------------------------------
# 2. Helper function to aggregate volume and churn rate
# ----------------------------------------------------
def get_segment_metrics(col, custom_order=None):
    df_grouped = customer_profile.groupby(col, observed=False).agg(
        total_customers=('customer_id', 'count'),
        churn_rate=('is_churned', lambda x: x.mean() * 100)
    ).reset_index()

    if custom_order:
        df_grouped[col] = pd.Categorical(df_grouped[col], categories=custom_order, ordered=True)
        df_grouped = df_grouped.sort_values(col)
    else:
        df_grouped = df_grouped.sort_values(by='total_customers', ascending=False)

    return df_grouped

# Prepare all segment DataFrames
ind_df = get_segment_metrics('industry')
reg_df = get_segment_metrics('region')
type_df = get_segment_metrics('customer_type', custom_order=['SMB', 'Mid-market', 'Enterprise'])
plan_df = get_segment_metrics('plan_type', custom_order=['Basic', 'Pro', 'Enterprise'])

# ----------------------------------------------------
# 3. Plot 4x2 side-by-side comparison grid
# ----------------------------------------------------
fig, axes = plt.subplots(4, 2, figsize=(16, 18))

def annotate_bars(ax, is_pct=False):
    for p in ax.patches:
        height = p.get_height()
        if height > 0:
            label = f'{height:.1f}%' if is_pct else f'{int(height):,}'
            ax.annotate(label,
                        (p.get_x() + p.get_width() / 2., height),
                        ha='center', va='bottom',
                        fontsize=10, fontweight='bold',
                        xytext=(0, 3), textcoords='offset points')

# Row 1: Industry
sns.barplot(data=ind_df, x='industry', y='total_customers', hue='industry', legend=False, palette='Blues_r', ax=axes[0, 0])
axes[0, 0].set_title('Total Customers by Industry', fontsize=12, fontweight='bold')
axes[0, 0].set_ylabel('Total Customers')
axes[0, 0].set_ylim(0, ind_df['total_customers'].max() * 1.18)
annotate_bars(axes[0, 0], is_pct=False)

sns.barplot(data=ind_df, x='industry', y='churn_rate', hue='industry', legend=False, palette='Reds_r', ax=axes[0, 1])
axes[0, 1].set_title('Churn Rate (%) by Industry', fontsize=12, fontweight='bold')
axes[0, 1].set_ylabel('Churn Rate (%)')
axes[0, 1].set_ylim(0, ind_df['churn_rate'].max() * 1.18)
annotate_bars(axes[0, 1], is_pct=True)

# Row 2: Region
sns.barplot(data=reg_df, x='region', y='total_customers', hue='region', legend=False, palette='Greens_r', ax=axes[1, 0])
axes[1, 0].set_title('Total Customers by Region', fontsize=12, fontweight='bold')
axes[1, 0].set_ylabel('Total Customers')
axes[1, 0].set_ylim(0, reg_df['total_customers'].max() * 1.18)
annotate_bars(axes[1, 0], is_pct=False)

sns.barplot(data=reg_df, x='region', y='churn_rate', hue='region', legend=False, palette='Oranges_r', ax=axes[1, 1])
axes[1, 1].set_title('Churn Rate (%) by Region', fontsize=12, fontweight='bold')
axes[1, 1].set_ylabel('Churn Rate (%)')
axes[1, 1].set_ylim(0, reg_df['churn_rate'].max() * 1.18)
annotate_bars(axes[1, 1], is_pct=True)

# Row 3: Customer Type
sns.barplot(data=type_df, x='customer_type', y='total_customers', hue='customer_type', legend=False, palette='Blues_r', ax=axes[2, 0])
axes[2, 0].set_title('Total Customers by Customer Type', fontsize=12, fontweight='bold')
axes[2, 0].set_ylabel('Total Customers')
axes[2, 0].set_ylim(0, type_df['total_customers'].max() * 1.18)
annotate_bars(axes[2, 0], is_pct=False)

sns.barplot(data=type_df, x='customer_type', y='churn_rate', hue='customer_type', legend=False, palette='Purples_r', ax=axes[2, 1])
axes[2, 1].set_title('Churn Rate (%) by Customer Type', fontsize=12, fontweight='bold')
axes[2, 1].set_ylabel('Churn Rate (%)')
axes[2, 1].set_ylim(0, type_df['churn_rate'].max() * 1.18)
annotate_bars(axes[2, 1], is_pct=True)

# Row 4: Plan Type
sns.barplot(data=plan_df, x='plan_type', y='total_customers', hue='plan_type', legend=False, palette='Greens_r', ax=axes[3, 0])
axes[3, 0].set_title('Total Customers by Plan Type', fontsize=12, fontweight='bold')
axes[3, 0].set_ylabel('Total Customers')
axes[3, 0].set_ylim(0, plan_df['total_customers'].max() * 1.18)
annotate_bars(axes[3, 0], is_pct=False)

sns.barplot(data=plan_df, x='plan_type', y='churn_rate', hue='plan_type', legend=False, palette='Reds_r', ax=axes[3, 1])
axes[3, 1].set_title('Churn Rate (%) by Plan Type', fontsize=12, fontweight='bold')
axes[3, 1].set_ylabel('Churn Rate (%)')
axes[3, 1].set_ylim(0, plan_df['churn_rate'].max() * 1.18)
annotate_bars(axes[3, 1], is_pct=True)

plt.tight_layout()

# Render plot in Streamlit app
st.pyplot(fig)
plt.close(fig)

"""**Average Revenue Per User (ARPU) & Price Point Distribution by Plan**

**Objective** Assess how much money our business earns on average from each customer across our three subscription tiers: Basic, Pro, and Enterprise.
This helps us understand how our pricing strategy is working, how customer volume is spread out, and how much extra value we gain when a customer upgrades to a higher plan.
**Technical Approach**
Calculated Key Financial Metrics per Plan:
Average Monthly Revenue (ARPU): The typical monthly earnings per customer record.
Median Revenue: The middle price point for each tier.
Price Boundaries: The minimum and maximum price points charged per plan.
Total Monthly Records: The total volume of active monthly subscriptions per plan.
Organized & Formatted: Arranged plans in order (Basic → Pro → Enterprise) and formatted all dollar values ($) clearly.
Visualized Results: Built a bar chart showing average revenue per user (ARPU) side-by-side with exact dollar labels above each bar.

**Key Results & Insights**
Basic Plan (High Volume, Low Price):
Average Revenue (ARPU): $35.40/month (Median: $29.00).
Price Range: $29.00 to $99.00.
Volume Share: 27,855 active monthly records (nearly 50% of all monthly customer activity).
Pro Plan (Balanced Mid-Tier):
Average Revenue (ARPU): $162.00/month (Median: $199.00).
Price Range: $99.00 to $299.00.
Volume Share: 16,315 active monthly records (29.2% of total activity).
Enterprise Plan (High Value Premium Tier):
Average Revenue (ARPU): $757.80/month (Median: $999.00).
Price Range: $299.00 to $999.00.
Volume Share: 9,851 active monthly records (17.7% of total activity).

**Business Takeaway**
Our pricing structure creates a massive revenue jump at each upgrade tier:
Upgrading a customer from Basic to Pro increases average monthly revenue by ~4.6x (from ~$35 to ~$162).
Upgrading a customer from Pro to Enterprise increases average monthly revenue by ~4.7x (from ~$162 to ~$758).
Encouraging Basic and Pro users to upgrade to higher tiers is one of the most powerful levers we have for growing overall revenue.
"""

# Cost per plan
# Set overall style
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 11})

st.subheader("Monthly Revenue & Pricing Breakdown by Plan Type")

# 1. Merge status data with customer plan types (if not already merged)
if 'plan_type' in status_df.columns:
    df_revenue = status_df
else:
    df_revenue = status_df.merge(customers_df[['customer_id', 'plan_type']], on='customer_id', how='left')

# 2. Calculate revenue breakdown per plan type
plan_pricing = df_revenue.groupby('plan_type', observed=False).agg(
    avg_monthly_revenue=('monthly_revenue', 'mean'),
    median_monthly_revenue=('monthly_revenue', 'median'),
    min_monthly_revenue=('monthly_revenue', 'min'),
    max_monthly_revenue=('monthly_revenue', 'max'),
    total_active_records=('customer_id', 'count')
).reset_index()

# Enforce logical ordering: Basic -> Pro -> Enterprise
plan_order = ['Basic', 'Pro', 'Enterprise']
plan_pricing['plan_type'] = pd.Categorical(plan_pricing['plan_type'], categories=plan_order, ordered=True)
plan_pricing = plan_pricing.sort_values('plan_type').reset_index(drop=True)

# ----------------------------------------------------
# 3. Display Summary Table
# ----------------------------------------------------
formatted_pricing = plan_pricing.copy()
for col in ['avg_monthly_revenue', 'median_monthly_revenue', 'min_monthly_revenue', 'max_monthly_revenue']:
    formatted_pricing[col] = formatted_pricing[col].apply(lambda x: f"${x:,.2f}")

st.write("**Monthly Revenue Breakdown Table**")
st.dataframe(formatted_pricing, use_container_width=True)

# ----------------------------------------------------
# 4. Visual Comparison: Average Revenue per Plan Type
# ----------------------------------------------------
fig, ax = plt.subplots(figsize=(9, 5))

sns.barplot(
    data=plan_pricing,
    x='plan_type',
    y='avg_monthly_revenue',
    hue='plan_type',
    legend=False,
    palette='Blues_r',
    ax=ax
)

# Annotate bars with exact dollar amounts
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(
            f"${height:,.2f}",
            (p.get_x() + p.get_width() / 2., height),
            ha='center', va='bottom',
            fontsize=11, fontweight='bold',
            xytext=(0, 5), textcoords='offset points'
        )

ax.set_title('Average Monthly Revenue (ARPU) by Plan Type', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Plan Type', fontsize=12, labelpad=10)
ax.set_ylabel('Average Monthly Revenue ($)', fontsize=12, labelpad=10)
ax.set_ylim(0, plan_pricing['avg_monthly_revenue'].max() * 1.18)

# Format y-axis ticks as currency
ax.yaxis.set_major_formatter('${x:,.0f}')

plt.tight_layout()

# Render plot in Streamlit app
st.pyplot(fig)
plt.close(fig)

"""# **Monthly Recurring Revenue (MRR) Loss Analysis by Subscription Plan**
**Objective**
Quantify the total financial impact of customer churn by calculating monthly recurring revenue (MRR) loss across subscription tiers (Basic, Pro, and Enterprise), identifying high-value risk exposure and revenue concentration patterns.

**Technical Approach**
Identified Churned Accounts: Looked at each customer's final active record to flag accounts that canceled before the latest month in our dataset.
Grouped by Subscription Tier: Categorized canceled accounts into Basic, Pro, and Enterprise plans.
Calculated the Financial Metrics:
Total churned customers per plan.
Total monthly revenue lost ($).
Average revenue lost per canceled account ($).
Percentage share of total monthly revenue loss (%).
Visualized the Losses: Created an annotated bar chart displaying the exact dollar loss and account counts side-by-side for clear comparison.

**Key Results & Insights**
Total Revenue Lost: $265,876 per month across 1,634 churned accounts.

Enterprise Plan Exposure (Biggest Financial Risk): Accounts for 62.8 percent of total revenue loss ($166,854/month).Represents only 15.1 percent of canceled accounts (246 accounts), but loses an average of $678.27 per account.

Pro Plan Loss: Accounts for 25.6 percent of revenue loss ($67,949/month) across 451 accounts (~$150.66 per account).

Basic Plan Volume: Has the highest number of cancellations (937 accounts / 57.3% of total volume), but only accounts for 11.6 percent of dollar loss ($31,073/month) because of its low monthly price ($33.16 per account).

**Business Takeaway**
Focus retention efforts on Enterprise accounts. Saving just 1 Enterprise customer recovers roughly the same monthly revenue as keeping 20 Basic customers. Dedicated account management and VIP customer support for Enterprise clients will yield the highest ROI on retention spending.
"""

#Total revenue lost due to churn

# Set visual style
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 11})

st.subheader("Monthly Revenue (MRR) Lost to Churn by Plan Type")

# ----------------------------------------------------
# 1. Fetch data & identify churned customers
# ----------------------------------------------------
# Merge plan_type from customers_df if missing in status_df
if 'plan_type' in status_df.columns:
    df_status = status_df.copy()
else:
    df_status = status_df.merge(customers_df[['customer_id', 'plan_type']], on='customer_id', how='left')

df_status['activity_month'] = pd.to_datetime(df_status['activity_month'])

# Identify the dataset's latest active month
max_month = df_status['activity_month'].max()

# Get each customer's final active record
last_customer_records = (
    df_status.sort_values('activity_month')
    .groupby('customer_id')
    .last()
    .reset_index()
)

# Flag churned accounts (last active month was before max_month)
last_customer_records['is_churned'] = last_customer_records['activity_month'] < max_month

# Filter down to churned accounts only
churned_df = last_customer_records[last_customer_records['is_churned']].copy()

# ----------------------------------------------------
# 2. Aggregate lost revenue by Plan Type
# ----------------------------------------------------
plan_mrr_loss = churned_df.groupby('plan_type', observed=False).agg(
    churned_customers=('customer_id', 'count'),
    total_lost_mrr=('monthly_revenue', 'sum'),
    avg_lost_mrr=('monthly_revenue', 'mean')
).reset_index()

# Calculate % share of total lost MRR
total_loss_all_plans = plan_mrr_loss['total_lost_mrr'].sum()
plan_mrr_loss['pct_of_total_loss'] = (
    (plan_mrr_loss['total_lost_mrr'] / total_loss_all_plans) * 100 
    if total_loss_all_plans > 0 else 0
)

# Enforce logical plan order
plan_order = ['Basic', 'Pro', 'Enterprise']
plan_mrr_loss['plan_type'] = pd.Categorical(plan_mrr_loss['plan_type'], categories=plan_order, ordered=True)
plan_mrr_loss = plan_mrr_loss.sort_values('plan_type').reset_index(drop=True)

# ----------------------------------------------------
# 3. Display KPI Metric & Summary Table
# ----------------------------------------------------
st.metric("Total Monthly Revenue Lost (All Plans)", f"${total_loss_all_plans:,.2f}")

formatted_table = plan_mrr_loss.copy()
formatted_table['total_lost_mrr'] = formatted_table['total_lost_mrr'].apply(lambda x: f"${x:,.2f}")
formatted_table['avg_lost_mrr'] = formatted_table['avg_lost_mrr'].apply(lambda x: f"${x:,.2f}")
formatted_table['pct_of_total_loss'] = formatted_table['pct_of_total_loss'].apply(lambda x: f"{x:.1f}%")

st.write("**Lost MRR Breakdown Table**")
st.dataframe(formatted_table, use_container_width=True)

# ----------------------------------------------------
# 4. Plot Lost MRR Chart
# ----------------------------------------------------
fig, ax = plt.subplots(figsize=(10, 6))

sns.barplot(
    data=plan_mrr_loss,
    x='plan_type',
    y='total_lost_mrr',
    hue='plan_type',
    legend=False,
    palette='Reds_r',
    ax=ax
)

# Annotate bars with dollar amounts and customer counts
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        # Match height to plan row to pull customer count
        matching_rows = plan_mrr_loss[plan_mrr_loss['total_lost_mrr'] == height]
        if not matching_rows.empty:
            plan_row = matching_rows.iloc[0]
            label = f"${height:,.0f}\n({int(plan_row['churned_customers'])} accounts)"

            ax.annotate(
                label,
                (p.get_x() + p.get_width() / 2., height),
                ha='center', va='bottom',
                fontsize=10, fontweight='bold',
                xytext=(0, 5), textcoords='offset points'
            )

ax.set_title('Total Monthly Revenue (MRR) Lost to Churn by Plan Type', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Plan Type', fontsize=12, labelpad=10)
ax.set_ylabel('Total Lost Revenue ($)', fontsize=12, labelpad=10)
ax.set_ylim(0, plan_mrr_loss['total_lost_mrr'].max() * 1.22 if not plan_mrr_loss.empty else 100)

# Format y-axis ticks as currency
ax.yaxis.set_major_formatter('${x:,.0f}')

plt.tight_layout()

# Render plot in Streamlit app
st.pyplot(fig)
plt.close(fig)

"""# Data Ingestion

**Multi-Table Data Ingestion & Alignment**
**Objective**
Integrate five disjointed relational database tables (gfcustomer_information, gfmonthly_status, gfusage_data, gffeedback_data, and gfengagement_data) into a single master analytical dataset without losing row history.

**Technical Approach**
Built the Main Timeline: Used the monthly status table (gfmonthly_status) as our primary backbone so every row represents a customer in a specific month.
Standardized Date Names: Renamed different date labels (like feedback_month and engagement_month) to a single standard column: activity_month.
Prevented Duplicate Info: Kept permanent customer details (like region and industry) solely in the customer information table to avoid cluttered, duplicate columns.
Matched Information Accurately: Linked usage, feedback, and engagement records using the customer's ID and the specific month.
Filled in the Gaps: When a customer had no recorded usage or feedback in a given month, we filled those missing activity counts with 0 rather than leaving blank spaces.
**Key Results**
Master Dataset Size: 55,808 total monthly records, structured cleanly over time.
Complete Customer Coverage: All 5,000 unique customers were successfully linked without losing anyone.
Comprehensive Metrics: 25 total attributes capturing customer profiles, monthly product usage, satisfaction scores, and campaign responses side-by-side.

**Business Takeaway**
By combining these isolated tables into a single master view, we now have a complete 360-degree picture of each customer's monthly journey, making it much easier to analyze retention, usage patterns, and churn risks.
"""

# ----------------------------------------------------
# 1. Cached Data Ingestion & Merging Function
# ----------------------------------------------------
@st.cache_data
def load_and_build_analytical_df():
    # Load raw CSV tables
    df_customers = pd.read_csv('gfcustomer_information.csv')
    df_status    = pd.read_csv('gfmonthly_status.csv')
    df_usage     = pd.read_csv('gfusage_data.csv')
    df_feedback  = pd.read_csv('gffeedback_data.csv')
    df_engagement= pd.read_csv('gfengagement_data.csv')

    # Align month column names across all datasets to 'activity_month'
    df_feedback_clean = df_feedback.rename(columns={'feedback_month': 'activity_month'})
    df_engagement_clean = df_engagement.rename(columns={'engagement_month': 'activity_month'})

    # Convert date columns to proper datetime format
    date_cols = ['subscription_date', 'cohort', 'activity_month']
    for df in [df_customers, df_status, df_usage, df_feedback_clean, df_engagement_clean]:
        for col in date_cols:
            if col in df.columns:
                df[col] = pd.to_datetime(df[col])

    # Drop redundant static attributes from df_status to prevent _x / _y duplicate columns
    status_core_cols = [
        col for col in df_status.columns
        if col not in ['cohort', 'industry', 'region', 'customer_type', 'plan_type']
    ]
    df_status_clean = df_status[status_core_cols]

    # Sequential Left Joins (Building Monthly Analytical Spine)
    analytical_df = pd.merge(df_status_clean, df_customers, on='customer_id', how='left')

    analytical_df = pd.merge(
        analytical_df,
        df_usage,
        on=['customer_id', 'activity_month'],
        how='left',
        suffixes=('', '_usage')
    )

    analytical_df = pd.merge(
        analytical_df,
        df_feedback_clean,
        on=['customer_id', 'activity_month'],
        how='left'
    )

    analytical_df = pd.merge(
        analytical_df,
        df_engagement_clean,
        on=['customer_id', 'activity_month'],
        how='left'
    )

    # Drop redundant 'months_since_sub_usage' if generated during join
    if 'months_since_sub_usage' in analytical_df.columns:
        analytical_df.drop(columns=['months_since_sub_usage'], inplace=True)

    # Impute Missing Values Post-Merge
    zero_fill_cols = [
        'session_duration', 'feature_crm', 'feature_email_campaigns',
        'feature_analytics', 'feature_automation', 'engagement_count',
        'response_rate', 'avg_response_rate'
    ]

    for col in zero_fill_cols:
        if col in analytical_df.columns:
            analytical_df[col] = analytical_df[col].fillna(0)

    return df_customers, df_status, df_usage, df_feedback, df_engagement, analytical_df

# Call function once into cached memory
customers_df, status_df, usage_df, feedback_df, engagement_df, model_df = load_and_build_analytical_df()

# ----------------------------------------------------
# 2. UI Ingestion Summary & Verification
# ----------------------------------------------------
st.subheader("⚙️ Data Ingestion & Pipeline Summary")

# KPI Summary Cards
col1, col2, col3 = st.columns(3)
col1.metric("Master Dataset Rows", f"{len(model_df):,}")
col2.metric("Unique Customers Retained", f"{model_df['customer_id'].nunique():,}")
col3.metric("Total Joined Features", len(model_df.columns))

# Optional details in expandable panel
with st.expander("🔍 Inspect Master Analytical Dataset"):
    st.write("**Feature List:**")
    st.write(list(model_df.columns))
    st.write("**Dataset Preview (First 5 Rows):**")
    st.dataframe(model_df.head(), use_container_width=True)

"""**Subscription Cohort Definition & Tenure Calculation**
**Objective**
Organize customers into groups based on when they joined and track how long they've stayed Growth Flow.
**Technical Approach**
1. Grouping Customers by "Signup Month" (Cohorts)
What it does: Instead of looking at exact calendar dates (like April 12, 2024), it rounds everyone’s join date to the 1st of that month (April 1, 2024).
Why it matters: This puts all customers who signed up in April 2024 into one group. It lets us compare how the "April Group" behaves compared to the "May Group" over time.
2. Calculating Customer "Tenure" (Months as a Customer)
What it does: It counts how many months have passed between when a customer signed up and each month they used our service.
Month 0: Their very first month with us.
Month 1: Their second month with us.
Month 9: They’ve been with us for 9 months.
Why it matters: This turns calendar dates into an easy timeline so we can answer questions like: "How many customers leave after 3 months?" or "Does customer spending drop off after Month 6?"

**Results Show**
Steady Growth: We are consistently gaining around 200 to 230 new customers every single month.
Best Performing Signup Months: August 2024 was our biggest acquisition month (232 new customers), followed closely by May 2024 (229 new customers).

**The Big Takeaway**
This step prepares our data so we can clearly see customer loyalty and retention trends. By organizing customers by signup month and measuring their tenure step-by-step, we can easily spot when users are most likely to drop off and step in to keep them.
"""

# Cohort Creation and Monthly subscription

# Ensure date columns are in datetime format
model_df['activity_month'] = pd.to_datetime(model_df['activity_month'])
model_df['subscription_date'] = pd.to_datetime(model_df['subscription_date'])

# ----------------------------------------------------
# 1. Create Monthly Subscription Cohort
# ----------------------------------------------------
# Option A: Based on official subscription_date (Normalized to 1st of month)
model_df['subscription_cohort'] = model_df['subscription_date'].dt.to_period('M').dt.to_timestamp()

# Option B: Alternative - Based on customer's first recorded activity month in dataset
first_activity = model_df.groupby('customer_id')['activity_month'].transform('min')
model_df['first_activity_cohort'] = first_activity

# ----------------------------------------------------
# 2. Calculate Months Since Subscription
# ----------------------------------------------------
# Precise month-difference calculation between activity_month and subscription cohort
model_df['months_since_subscription'] = (
    (model_df['activity_month'].dt.year - model_df['subscription_cohort'].dt.year) * 12 +
    (model_df['activity_month'].dt.month - model_df['subscription_cohort'].dt.month)
)

# Replace any negative values with 0 (for edge cases where activity occurs in signup month)
model_df['months_since_subscription'] = model_df['months_since_subscription'].clip(lower=0)

# ----------------------------------------------------
# 3. UI Verification & Inspection
# ----------------------------------------------------
st.subheader("Cohort & Tenure Feature Engineering")

# Verification preview inside expandable drawer
with st.expander("🔍 Inspect Cohort & Tenure Output Data"):
    st.write("**Sample Cohorts & Months Since Subscription:**")
    st.dataframe(
        model_df[[
            'customer_id',
            'subscription_date',
            'subscription_cohort',
            'activity_month',
            'months_since_subscription'
        ]].head(10),
        use_container_width=True
    )

    # Cohort Size Distribution
    st.write("**Customer Count per Subscription Cohort (Top 10):**")
    cohort_counts = model_df.groupby('subscription_cohort')['customer_id'].nunique().reset_index()
    cohort_counts.columns = ['Subscription Cohort', 'Unique Customer Count']
    cohort_counts['Subscription Cohort'] = cohort_counts['Subscription Cohort'].dt.strftime('%Y-%m')
    
    st.dataframe(cohort_counts.head(10), use_container_width=True)

"""**Customer Retention Matrix & Heatmap Analysis**
**Objective**
This code tracks how long different groups of customers stay active over time.
It organizes customers by the month they signed up (their "cohort") and tracks what percentage of each group is still paying and using our service in Month 1, Month 2, Month 3, and beyond.
**Technical Approach**
Group by Signup Month: Groups every customer based on the month they joined (e.g., all January 2024 signups together).
Track Monthly Activity: Checks each month after signup to see if the customer is still active.
Calculate Retention Percentages: Divides active customers in any given month by the starting total for that signup group to calculate the retention rate (100% starting point).
Visualize as a Heatmap: Plots the results in a grid where dark blue represents high retention and lighter shades show where customers begin to leave (churn).

**Key Takeaways**
Strong Initial Onboarding (Month 1):
Near-perfect retention in the first month across almost all cohorts (99%−100%), showing that new customers get immediate value during initial onboarding.
Gradual Early Drop-Off (Months 2–6):
By Month 3, retention drops slightly to around 93%−97%.
By Month 6, retention settles around 85%−91%, showing a predictable, steady decay rather than a sudden drop.
Long-Term Loyalty Base (Months 12+):
After 1 year (Month 12), roughly 70%−81% of customers remain active.
Retention flattens out around the 70%−75% range for mature accounts (Months 13–20), pointing to a stable core group of loyal long-term subscribers.
Tail-End Drop Off (Final Month):
The sharp drop in the final month column (down to 48%−55%) reflects the cutoff point of the dataset rather than a sudden change in customer behavior.

**Business Takeaway**
Our business enjoys strong early customer retention and a solid long-term foundation, keeping over 70% of subscribers active past the one-year mark. Retention efforts should focus on months 6 through 12 to help more customers cross into that loyal, long-term group.
"""

# Cohort Retention Matrix & Heatmap

# Set visual styling
sns.set_theme(style="white")
plt.rcParams.update({'font.size': 10})

st.subheader("Customer Cohort Retention Analysis")

# ----------------------------------------------------
# 1. Prepare Data & Ensure Cohort Indexing
# ----------------------------------------------------
# Ensure dates are datetime objects
model_df['activity_month'] = pd.to_datetime(model_df['activity_month'])
model_df['subscription_date'] = pd.to_datetime(model_df['subscription_date'])

# Assign Cohort (1st of signup month)
model_df['cohort_month'] = model_df['subscription_date'].dt.to_period('M').dt.to_timestamp()

# Calculate Cohort Index (0 = Signup Month, 1 = Month 1, etc.)
model_df['cohort_index'] = (
    (model_df['activity_month'].dt.year - model_df['cohort_month'].dt.year) * 12 +
    (model_df['activity_month'].dt.month - model_df['cohort_month'].dt.month)
)

# Filter out active flags if applicable
active_df = model_df[model_df['is_active'] == 1] if 'is_active' in model_df.columns else model_df

# ----------------------------------------------------
# 2. Build Count Matrix & Calculate Retention Rates (%)
# ----------------------------------------------------
# Pivot to get count of unique active customers per cohort per month index
cohort_counts = active_df.pivot_table(
    index='cohort_month',
    columns='cohort_index',
    values='customer_id',
    aggfunc='nunique'
)

# Extract initial cohort size (Month 0 count)
cohort_sizes = cohort_counts.iloc[:, 0]

# Calculate percentage retention matrix
retention_matrix = cohort_counts.divide(cohort_sizes, axis=0) * 100

# Format index as clean YYYY-MM labels
retention_matrix.index = retention_matrix.index.strftime('%Y-%m')

# ----------------------------------------------------
# 3. Plot Cohort Retention Heatmap
# ----------------------------------------------------
fig, ax = plt.subplots(figsize=(14, 8))

sns.heatmap(
    retention_matrix,
    annot=True,
    fmt='.0f',
    cmap='YlGnBu',
    cbar_kws={'label': 'Retention Rate (%)'},
    linewidths=0.5,
    vmin=0,
    vmax=100,
    ax=ax
)

ax.set_title('Monthly Customer Cohort Retention Matrix (%)', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Months Since Subscription (Cohort Index)', fontweight='bold', labelpad=10)
ax.set_ylabel('Subscription Cohort (Signup Month)', fontweight='bold', labelpad=10)
plt.yticks(rotation=0)

plt.tight_layout()

# Render heat map in Streamlit
st.pyplot(fig)
plt.close(fig)

# ----------------------------------------------------
# 4. Overall Monthly Retention Rate Summary
# ----------------------------------------------------
st.subheader("Average Retention Rate Decay")

avg_retention = retention_matrix.mean(axis=0).reset_index()
avg_retention.columns = ['Months Since Signup', 'Avg Retention Rate (%)']
avg_retention['Avg Retention Rate (%)'] = avg_retention['Avg Retention Rate (%)'].round(2)

col1, col2 = st.columns([1, 2])

with col1:
    st.write("**Average Retention Data**")
    st.dataframe(avg_retention, use_container_width=True)

with col2:
    st.write("**Retention Curve**")
    st.line_chart(avg_retention.set_index('Months Since Signup'))
"""# Feature Engineering

Feature Engineering for Customer-Level Model Snapshot Dataset (5,000 Rows)

***Objective:***
Condense monthly activity history (~55,000 rows) into one single master table with exactly 5,000 rows (one row per customer).

***Technical Approach:***
Calculate Total Tenure & Churn Status: Determine each customer's final active month and sets our target variable (is_churned = 1 for canceled accounts, 0 for active accounts).
Pull Static Demographics: Extracts fixed customer details like company size, industry, region, and customer segment.
Aggregates Lifetime Habits: Computes average monthly revenue, typical session lengths, overall feature usage counts (CRM, Email, Analytics, Automation), and latest feedback ratings.
Engineers Early Warning Signals (session_duration_decay_ratio): Compares usage in a customer's last 2 active months against their lifetime average to detect sudden drops in engagement right before they churn.
Handles Missing Ratings: Fills in blank satisfaction/NPS scores with median values for customers who never submitted feedback.

***Result***
Total Dataset Volume: 5,000 unique customer rows
Feature Dimensionality: 19 clean predictor columns capturing demographics, usage averages, sentiment scores, and pre-churn decay metrics.
Target Variable Balance (is_churned):
Churned Accounts (is_churned = 1): 1,634 customers (32.68% of the customer base).
Active Accounts (is_churned = 0): 3,366 customers (67.32% retention rate).
"""

# import streamlit as st
import pandas as pd

@st.cache_data
def build_master_model_snapshot(df_analytical):
    analytical_df = df_analytical.copy()

    # ----------------------------------------------------
    # 1. Determine Global Max Month & Account Status
    # ----------------------------------------------------
    max_global_month = analytical_df['activity_month'].max()

    # Handle key naming variation safely
    tenure_col = 'months_since_subscription' if 'months_since_subscription' in analytical_df.columns else 'months_since_sub'

    customer_tenure = (
        analytical_df.groupby('customer_id')
        .agg(
            last_active_month=('activity_month', 'max'),
            total_months_active=(tenure_col, 'max'),
            first_subscription_date=('subscription_date', 'min'),
        )
        .reset_index()
    )

    # Target variable: is_churned (1 = canceled prior to global max month, 0 = active)
    customer_tenure['is_churned'] = (
        customer_tenure['last_active_month'] < max_global_month
    ).astype(int)

    # ----------------------------------------------------
    # 2. Static Profile Features
    # ----------------------------------------------------
    # Dynamically select static profile columns present in dataset
    possible_static = ['customer_id', 'company_size', 'industry', 'region', 'customer_type']
    static_profile_cols = [col for col in possible_static if col in analytical_df.columns]

    df_static_profiles = analytical_df[static_profile_cols].drop_duplicates(
        subset=['customer_id']
    )

    # ----------------------------------------------------
    # 3. Aggregated Lifetime Baseline Metrics
    # ----------------------------------------------------
    # Pre-calculate composite platform usage per record
    feature_cols = ['feature_crm', 'feature_email_campaigns', 'feature_analytics', 'feature_automation']
    existing_features = [c for c in feature_cols if c in analytical_df.columns]
    
    analytical_df['total_platform_uses_record'] = analytical_df[existing_features].sum(axis=1)

    lifetime_agg = (
        analytical_df.groupby('customer_id')
        .agg(
            latest_plan_type=('plan_type', 'last'),
            avg_monthly_revenue=('monthly_revenue', 'mean'),
            avg_session_duration=('session_duration', 'mean'),
            total_platform_uses=('total_platform_uses_record', 'sum'),
            avg_engagement_count=('engagement_count', 'mean'),
            engagement_rate=('response_rate', 'mean'),
            latest_satisfaction_score=('satisfaction_score', 'last'),
            latest_nps_score=('nps_score', 'last'),
        )
        .reset_index()
    )

    # ----------------------------------------------------
    # 4. Feature Engineering: Pre-Churn Trend & Decay Signals
    # ----------------------------------------------------
    sorted_df = analytical_df.sort_values(['customer_id', 'activity_month'])

    recent_2mo_metrics = (
        sorted_df.groupby('customer_id')
        .tail(2)
        .groupby('customer_id')
        .agg(
            recent_2mo_avg_session=('session_duration', 'mean'),
            recent_2mo_avg_revenue=('monthly_revenue', 'mean'),
            recent_2mo_engagement_rate=('response_rate', 'mean'),
            recent_2mo_engagement_count=('engagement_count', 'mean'),
        )
        .reset_index()
    )

    lifetime_agg = pd.merge(lifetime_agg, recent_2mo_metrics, on='customer_id')

    # Trend Ratios (Recent 2-Mo Avg / Lifetime Avg)
    lifetime_agg['session_duration_decay_ratio'] = (
        lifetime_agg['recent_2mo_avg_session']
        / (lifetime_agg['avg_session_duration'] + 1e-5)
    ).round(3)

    lifetime_agg['revenue_trend_ratio'] = (
        lifetime_agg['recent_2mo_avg_revenue']
        / (lifetime_agg['avg_monthly_revenue'] + 1e-5)
    ).round(3)

    lifetime_agg['engagement_trend_ratio'] = (
        lifetime_agg['recent_2mo_engagement_rate']
        / (lifetime_agg['engagement_rate'] + 1e-5)
    ).round(3)

    lifetime_agg['outreach_volume_trend_ratio'] = (
        lifetime_agg['recent_2mo_engagement_count']
        / (lifetime_agg['avg_engagement_count'] + 1e-5)
    ).round(3)

    # Drop intermediate raw recent averages
    lifetime_agg.drop(
        columns=[
            'recent_2mo_avg_session',
            'recent_2mo_avg_revenue',
            'recent_2mo_engagement_rate',
            'recent_2mo_engagement_count',
        ],
        inplace=True,
    )

    # ----------------------------------------------------
    # 5. Master Model Snapshot Assembly
    # ----------------------------------------------------
    model_snapshot = pd.merge(df_static_profiles, customer_tenure, on='customer_id')
    model_snapshot = pd.merge(model_snapshot, lifetime_agg, on='customer_id')

    model_snapshot.drop(
        columns=['last_active_month', 'first_subscription_date'], inplace=True, errors='ignore'
    )

    # Impute missing sentiment scores with medians
    model_snapshot['latest_satisfaction_score'] = model_snapshot[
        'latest_satisfaction_score'
    ].fillna(model_snapshot['latest_satisfaction_score'].median())
    model_snapshot['latest_nps_score'] = model_snapshot['latest_nps_score'].fillna(
        model_snapshot['latest_nps_score'].median()
    )

    return model_snapshot

# Call cached feature engineering snapshot
master_model_df = build_master_model_snapshot(model_df)

# ----------------------------------------------------
# 6. Streamlit UI Display
# ----------------------------------------------------
st.subheader("Master Model Snapshot Assembly")

# Metrics Cards
col1, col2, col3 = st.columns(3)
col1.metric("Total Customer Records", f"{len(master_model_df):,}")
col2.metric("Engineered Features", len(master_model_df.columns))
col3.metric("Baseline Churn Rate", f"{master_model_df['is_churned'].mean() * 100:.1f}%")

# Expandable Feature Matrix Inspector
with st.expander("🔍 Inspect Master Model Feature Matrix"):
    st.write("**Engineered Feature List:**")
    st.write(list(master_model_df.columns))
    st.write("**Snapshot Data Preview:**")
    st.dataframe(master_model_df.head(10), use_container_width=True)

"""# **BASELINE MODELLING-Logistic regression and Random Forest**

**Baseline Modelling**
** Technical Approach**
Separated the Target: Took out the customer IDs and separated the answer key (is_churned) from the rest of the customer features.
Prepared the Data for the Model:
Text into Numbers: Converted text categories (like plan type or region) into 0s and 1s so the mathematical model could read them.
Equalized Scale: Scaled all numerical features (like revenue or session duration) to a standardized range so large numbers didn't overpower smaller ones.
Split the Data: Held back 20% of the dataset (1,000 customers) as a secret test set to evaluate the model fairly, using the other 80% (4,000 customers) to train it.
Trained & Evaluated the Model: Built a basic Logistic Regression model on the training data, asked it to predict churn on the 1,000 test customers, and printed out the score report.
** Results**
While the Logistic Regression model has a slightly higher raw accuracy (67.9% vs. 64.8%), it is practically useless for churn detection because it simply predicts that nearly everyone will stay active.
The Random Forest (Balanced) model successfully fixes this issue, boosting Churn Recall from 8.3% to 48.6%—meaning it captures nearly 6x more actual churners.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


@st.cache_resource
def train_and_eval_models(df):
    # ----------------------------------------------------
    # 1. Prepare Feature Set (X) and Target (y)
    # ----------------------------------------------------
    drop_cols = ['customer_id', 'is_churned']
    if 'cluster_k2' in df.columns:
        drop_cols.append('cluster_k2')

    X = df.drop(columns=[col for col in drop_cols if col in df.columns]).copy()
    y = df['is_churned']

    if 'cluster_segment' in X.columns:
        X['cluster_segment'] = X['cluster_segment'].astype('str')

    num_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
    cat_cols = X.select_dtypes(include=['object', 'category', 'string']).columns.tolist()

    # ----------------------------------------------------
    # 2. Encode Categoricals & Train-Test Split (80/20)
    # ----------------------------------------------------
    X_encoded = pd.get_dummies(X, columns=cat_cols, drop_first=True)

    X_train, X_test, y_train, y_test = train_test_split(
        X_encoded, y, test_size=0.20, random_state=42, stratify=y
    )

    scaler = StandardScaler()
    X_train_scaled = X_train.copy()
    X_test_scaled = X_test.copy()

    X_train_scaled[num_cols] = scaler.fit_transform(X_train[num_cols])
    X_test_scaled[num_cols] = scaler.transform(X_test[num_cols])

    # ----------------------------------------------------
    # 3. Train Models
    # ----------------------------------------------------
    lr_model = LogisticRegression(random_state=42, max_iter=1000)
    lr_model.fit(X_train_scaled, y_train)

    rf_model = RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        min_samples_split=5,
        class_weight='balanced',
        random_state=42,
        n_jobs=-1,
    )
    rf_model.fit(X_train, y_train)

    # ----------------------------------------------------
    # 4. Generate Predictions & Metrics
    # ----------------------------------------------------
    lr_pred = lr_model.predict(X_test_scaled)
    lr_proba = lr_model.predict_proba(X_test_scaled)[:, 1]

    rf_pred = rf_model.predict(X_test)
    rf_proba = rf_model.predict_proba(X_test)[:, 1]

    comparison_data = {
        'Metric': [
            'Accuracy',
            'Precision (Class 1)',
            'Recall (Class 1)',
            'F1-Score (Class 1)',
            'ROC-AUC',
        ],
        'Logistic Regression (Baseline)': [
            f'{accuracy_score(y_test, lr_pred):.4f}',
            f'{precision_score(y_test, lr_pred, pos_label=1):.4f}',
            f'{recall_score(y_test, lr_pred, pos_label=1):.4f}',
            f'{f1_score(y_test, lr_pred, pos_label=1):.4f}',
            f'{roc_auc_score(y_test, lr_proba):.4f}',
        ],
        'Random Forest (Balanced)': [
            f'{accuracy_score(y_test, rf_pred):.4f}',
            f'{precision_score(y_test, rf_pred, pos_label=1):.4f}',
            f'{recall_score(y_test, rf_pred, pos_label=1):.4f}',
            f'{f1_score(y_test, rf_pred, pos_label=1):.4f}',
            f'{roc_auc_score(y_test, rf_proba):.4f}',
        ],
    }

    comparison_df = pd.DataFrame(comparison_data)
    lr_report = classification_report(y_test, lr_pred)
    rf_report = classification_report(y_test, rf_pred)

    return comparison_df, lr_report, rf_report


# Run model pipeline
comp_df, lr_rep, rf_rep = train_and_eval_models(master_model_df)

# ----------------------------------------------------
# 5. UI Layout
# ----------------------------------------------------
st.subheader("Machine Learning Model Evaluation")

st.write("**Side-by-Side Model Performance Comparison:**")
st.dataframe(comp_df, use_container_width=True)

with st.expander("Detailed Classification Reports"):
    col1, col2 = st.columns(2)
    with col1:
        st.write("**Logistic Regression (Baseline)**")
        st.code(lr_rep)
    with col2:
        st.write("**Random Forest (Balanced)**")
        st.code(rf_rep)
        
"""# **Customer Segmentation (Kmeans Clustering)**

**Goal**
Evaluate the optimal number of clusters (k) using the Elbow Method (Within-Cluster Sum of Squares - WCSS) and Silhouette Score Analysis to group customers into distinct behavioral personas based on tenure, platform activity, sentiment, and pre-churn trend decay signals.
**Technical Approach**
2.1 Feature Selection & Engineering
Clustering was performed using 11 continuous attributes spanning four core dimensions:Tenure & Spend; Engagement & Product Depth; Sentiment Scores: latest_satisfaction_score; Pre-Churn Trend Ratios
2.2 Feature Scaling & Optimization Loop
Standardization: All 11 continuous features were standardized using StandardScaler (μ=0,σ=1)
Evaluation Sweep: K-Means models were evaluated across k=2 to k=10 using random initialization (n_init=10, random_state = 42).
**Results & Diagnostics**
The optimization evaluation yielded two primary structural peaks:
Plaintext
=== CLUSTER OPTIMIZATION METRICS ===
k =  3 | Silhouette Score: 0.2868 | WCSS: 34,628.95  <-- Global Peak
k =  8 | Silhouette Score: 0.2578 | WCSS: 20,252.16  <-- Granular Peak

**Final Implementation**
Selected Model: k=3 was chosen as the baseline segment feature (cluster_segment) for downstream predictive modeling to maximize cluster stability and mathematical separation without over-segmenting the dataset.
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

st.subheader("K-Means Clustering Optimization")

# ----------------------------------------------------
# 1. Prepare Feature Set & Cached Optimization Function
# ----------------------------------------------------
clustering_features = [
    'avg_session_duration',
    'total_months_active',
    'total_platform_uses',
    'avg_engagement_count',
    'engagement_rate',
    'latest_satisfaction_score',
    'latest_nps_score',
    'session_duration_decay_ratio',
    'revenue_trend_ratio',
    'engagement_trend_ratio',
    'outreach_volume_trend_ratio',
]

# Ensure required features exist in model_df
available_cluster_features = [f for f in clustering_features if f in master_model_df.columns]

@st.cache_data
def evaluate_kmeans_clusters(df, feature_list):
    X_cluster = df[feature_list].copy()
    
    # Scale features
    cluster_scaler = StandardScaler()
    X_cluster_scaled = cluster_scaler.fit_transform(X_cluster)

    k_range = range(2, 11)
    wcss = []
    silhouette_scores = []

    for k in k_range:
        kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
        kmeans.fit(X_cluster_scaled)

        wcss.append(kmeans.inertia_)
        score = silhouette_score(X_cluster_scaled, kmeans.labels_)
        silhouette_scores.append(score)

    metrics_df = pd.DataFrame({
        'Number of Clusters (k)': list(k_range),
        'Silhouette Score': [round(s, 4) for s in silhouette_scores],
        'Inertia (WCSS)': [round(w, 2) for w in wcss]
    })

    return metrics_df, k_range, wcss, silhouette_scores

# Run cached evaluation
cluster_metrics_df, k_range, wcss, silhouette_scores = evaluate_kmeans_clusters(
    master_model_df, available_cluster_features
)

# ----------------------------------------------------
# 2. Render Diagnostic Plots in Streamlit
# ----------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Elbow Method Plot
ax1.plot(k_range, wcss, marker='o', linestyle='--', color='#1f77b4')
ax1.set_title('Elbow Method (WCSS vs. K)', fontweight='bold')
ax1.set_xlabel('Number of Clusters (k)')
ax1.set_ylabel('Inertia (WCSS)')
ax1.grid(True, linestyle=':', alpha=0.6)

# Silhouette Score Plot
ax2.plot(k_range, silhouette_scores, marker='s', linestyle='--', color='#2ca02c')
ax2.set_title('Silhouette Score vs. K', fontweight='bold')
ax2.set_xlabel('Number of Clusters (k)')
ax2.set_ylabel('Silhouette Score')
ax2.grid(True, linestyle=':', alpha=0.6)

plt.tight_layout()

# Render plot on UI
st.pyplot(fig)
plt.close(fig)

# ----------------------------------------------------
# 3. Output Optimization Metrics
# ----------------------------------------------------
with st.expander("View Detailed Clustering Metrics Table"):
    st.dataframe(cluster_metrics_df, use_container_width=True)
    

"""### **Segmentation using K=3**

**Overview**
The k=3 K-Means model represents the primary macro-segmentation framework for GrowthFlow.
**Cluster Profiles Breakdown**

*Cluster 0:* High-Value Power Champions
Demographics: Highly concentrated in Large/Enterprise organizations (250+ employees) across Technology, Finance, and Healthcare sectors.
Plan Types: Predominantly Enterprise (45.2%) and Pro (30.0%) plans; 24.8% Basic.
Usage Behavior: Highest platform adoption (90.52 aggregate platform uses) and longest average session length (56.28 minutes). Strong outreach responsiveness (0.44).
Retention: Highest tenure (15.97 average active months) with stable behavioral decay ratios (≥1.0).
Revenue Contribution: Highest financial density at $505.69 average monthly revenue per account (16.8% of customer base).

*Cluster 1:* Core SMB / Entry Base
Demographics: Concentrated in Micro and Small businesses (1–10 employees) spanning varied SMB verticals.
Plan Types: Dominated by Basic plans (61.6%), followed by Pro (28.5%) and Enterprise (9.9%).
Usage Behavior: Lower platform activity (18.30 total platform uses) and shorter average session lengths (24.35 minutes).
Retention: Lower tenure (8.46 average active months) with higher exposure to early-stage onboarding drop-off.
Revenue Contribution: Lowest spend density at $109.47 average monthly revenue per account, but represents the majority cohort (64.5% of customer base).

*Cluster 2:* Mid-Market Growth & Transition
Demographics: Primary concentration in Mid-Sized organizations (11–250 employees).
Plan Types: Balanced plan distribution across Basic (49.7%), Pro (32.9%), and Enterprise (17.5%).
Usage Behavior: Steady product adoption (25.89 aggregate platform uses, 31.41-minute sessions) with high engagement responsiveness (0.42).
Retention: Moderate tenure (8.91 average active months).
Revenue Contribution: Moderate spend density at $201.61 average monthly revenue per account (18.7% of customer base).

**Strategic Business Recommendations**
Cluster 0: Assign dedicated Account Executives to secure multi-year annual renewals and protect top-tier revenue.
Cluster 1: Deploy automated, self-serve onboarding guides in Weeks 1–4 to reduce early account drop-off.
Cluster 2: Target accounts with feature enablement playbooks and incentives to drive Pro and Enterprise plan upgrades
"""
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

st.subheader("Final Customer Segmentation (K-Means, k = 3)")

# ----------------------------------------------------
# 1. Fit Final K-Means Model & Profile (Cached)
# ----------------------------------------------------
@st.cache_data
def run_final_clustering(df, optimal_k=3):
    model_df_clustered = df.copy()

    clustering_features = [
        'avg_session_duration',
        'total_months_active',
        'total_platform_uses',
        'avg_engagement_count',
        'engagement_rate',
        'latest_satisfaction_score',
        'latest_nps_score',
        'session_duration_decay_ratio',
        'revenue_trend_ratio',
        'engagement_trend_ratio',
        'outreach_volume_trend_ratio',
    ]

    # Verify existing features dynamically
    available_features = [f for f in clustering_features if f in model_df_clustered.columns]

    # Scale feature set
    cluster_scaler = StandardScaler()
    X_cluster_scaled = cluster_scaler.fit_transform(model_df_clustered[available_features])

    # Train K-Means & assign cluster labels
    kmeans_3 = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
    model_df_clustered['cluster_segment'] = kmeans_3.fit_predict(X_cluster_scaled)

    # Profiling numerical metrics
    profile_metrics = [
        'total_months_active',
        'avg_monthly_revenue',
        'is_churned',
        'avg_session_duration',
        'total_platform_uses',
        'avg_engagement_count',
        'engagement_rate',
        'latest_satisfaction_score',
        'latest_nps_score',
        'session_duration_decay_ratio',
        'revenue_trend_ratio',
    ]
    available_profile_metrics = [m for m in profile_metrics if m in model_df_clustered.columns]

    cluster_numerical_summary = (
        model_df_clustered.groupby('cluster_segment')[available_profile_metrics]
        .mean()
        .round(2)
        .reset_index()
    )

    if 'is_churned' in cluster_numerical_summary.columns:
        cluster_numerical_summary['churn_rate_%'] = (
            cluster_numerical_summary['is_churned'] * 100
        ).round(1)

    cluster_counts = (
        model_df_clustered['cluster_segment'].value_counts().sort_index().reset_index()
    )
    cluster_counts.columns = ['cluster_segment', 'customer_count']
    cluster_summary = pd.merge(
        cluster_counts, cluster_numerical_summary, on='cluster_segment'
    )

    return model_df_clustered, cluster_summary

# Execute cached clustering on master dataset
master_model_df, cluster_summary = run_final_clustering(master_model_df, optimal_k=3)

# ----------------------------------------------------
# 2. Display Numerical Profiling Table
# ----------------------------------------------------
st.write("**Customer Segment Profiles (Averages per Cluster):**")
st.dataframe(cluster_summary, use_container_width=True)

# ----------------------------------------------------
# 3. Categorical Profiling (Safe Dynamic Crosstabs)
# ----------------------------------------------------
with st.expander("Categorical & Demographic Distributions (%)"):
    cat_cols_to_check = ['latest_plan_type', 'industry', 'company_size']
    
    for col in cat_cols_to_check:
        if col in master_model_df.columns:
            st.write(f"**{col.replace('_', ' ').title()} Distribution (%)**")
            breakdown = (
                pd.crosstab(
                    master_model_df['cluster_segment'],
                    master_model_df[col],
                    normalize='index',
                )
                * 100
            ).round(1)
            st.dataframe(breakdown, use_container_width=True)

# ----------------------------------------------------
# 4. Visualizations: Churn Rate & Revenue Contribution
# ----------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Churn Rate Comparison
if 'churn_rate_%' in cluster_summary.columns:
    sns.barplot(
        data=cluster_summary,
        x='cluster_segment',
        y='churn_rate_%',
        hue='cluster_segment',
        legend=False,
        palette='Reds_d',
        ax=ax1,
    )
    ax1.set_title('Churn Rate (%) by Cluster Segment', fontweight='bold')
    ax1.set_xlabel('Cluster Segment')
    ax1.set_ylabel('Churn Rate (%)')
    for p in ax1.patches:
        if p.get_height() > 0:
            ax1.annotate(
                f'{p.get_height():.1f}%',
                (p.get_x() + p.get_width() / 2.0, p.get_height()),
                ha='center', va='bottom',
                xytext=(0, 3), textcoords='offset points',
                fontweight='bold'
            )

# Average Monthly Revenue Contribution
if 'avg_monthly_revenue' in cluster_summary.columns:
    sns.barplot(
        data=cluster_summary,
        x='cluster_segment',
        y='avg_monthly_revenue',
        hue='cluster_segment',
        legend=False,
        palette='Greens_d',
        ax=ax2,
    )
    ax2.set_title('Avg Monthly Revenue ($) by Cluster Segment', fontweight='bold')
    ax2.set_xlabel('Cluster Segment')
    ax2.set_ylabel('Avg Monthly Revenue ($)')
    for p in ax2.patches:
        if p.get_height() > 0:
            ax2.annotate(
                f'${p.get_height():.2f}',
                (p.get_x() + p.get_width() / 2.0, p.get_height()),
                ha='center', va='bottom',
                xytext=(0, 3), textcoords='offset points',
                fontweight='bold'
            )

plt.tight_layout()

# Render plot in Streamlit app
st.pyplot(fig)
plt.close(fig)

"""
# **Segmentation using k=8**

Cluster 0: "The Struggling Onboarders"
Cluster 1: "The Fading Veterans"
Cluster 2: "The Enterprise Champions"
Cluster 3: "The Steady SMB Backbone"
Cluster 4: "The Silent Subscribers"
Cluster 5: "The Mid-Market Powerhouses"
Cluster 6: "The Engaged Newcomers"
Cluster 7: "The Mid-Tier Regulars"

**To reduce Churn we need to Focus On: **

**Cluster 0 :** "The Struggling On boarders"
Brand-new accounts (active for under 3 months) who barely use the platform.
The Danger: 37pct Churn Rate. They get stuck early and cancel almost immediately.
Fix: Send automated "Getting Started" guides and offer live onboarding help in Week 1.

**Cluster 1 :** "The Fading Veterans"- Older accounts (~12 months active) on low spend who have stopped logging in. The Danger: 38pct Churn Rate (Highest). They have slowly outgrown or forgotten the tool.
Fix: Trigger automated re-engagement emails asking if they need help or new features.

**Cluster 6 :** "The Engaged Newcomers"
Newer accounts (~4 months active) who respond heavily to your outreach emails and check-ins. 32pct Churn Rate
The Status: High engagement, growing fast.
Fix: Keep feeding them training materials to make sure they turn into long-term Champions (Cluster 2).

🎯 Main Takeaway for Leadership
The single biggest insight from k=8 is that churn happens for two totally different reasons:
Early Friction (Cluster 0): Customers leaving in Month 1–3 because they can't figure out the software.
Late Decay (Cluster 1): Customers leaving in Month 12 because they slowly stopped using it.

"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

st.subheader("📊 Granular Customer Segmentation (K-Means, k = 8)")

# ----------------------------------------------------
# 1. Fit Final K-Means Model & Profile (Cached for k=8)
# ----------------------------------------------------
@st.cache_data
def run_granular_clustering(df, optimal_k=8):
    model_df_clustered = df.copy()

    clustering_features = [
        'avg_session_duration',
        'total_months_active',
        'total_platform_uses',
        'avg_engagement_count',
        'engagement_rate',
        'latest_satisfaction_score',
        'latest_nps_score',
        'session_duration_decay_ratio',
        'revenue_trend_ratio',
        'engagement_trend_ratio',
        'outreach_volume_trend_ratio',
    ]

    # Verify existing features dynamically
    available_features = [f for f in clustering_features if f in model_df_clustered.columns]

    # Scale feature set
    cluster_scaler = StandardScaler()
    X_cluster_scaled = cluster_scaler.fit_transform(model_df_clustered[available_features])

    # Train K-Means & assign cluster labels
    kmeans_8 = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
    model_df_clustered['cluster_segment'] = kmeans_8.fit_predict(X_cluster_scaled)

    # Profiling numerical metrics
    profile_metrics = [
        'total_months_active',
        'avg_monthly_revenue',
        'is_churned',
        'avg_session_duration',
        'total_platform_uses',
        'avg_engagement_count',
        'engagement_rate',
        'latest_satisfaction_score',
        'latest_nps_score',
        'session_duration_decay_ratio',
        'revenue_trend_ratio',
    ]
    available_profile_metrics = [m for m in profile_metrics if m in model_df_clustered.columns]

    cluster_numerical_summary = (
        model_df_clustered.groupby('cluster_segment')[available_profile_metrics]
        .mean()
        .round(2)
        .reset_index()
    )

    if 'is_churned' in cluster_numerical_summary.columns:
        cluster_numerical_summary['churn_rate_%'] = (
            cluster_numerical_summary['is_churned'] * 100
        ).round(1)

    cluster_counts = (
        model_df_clustered['cluster_segment'].value_counts().sort_index().reset_index()
    )
    cluster_counts.columns = ['cluster_segment', 'customer_count']
    cluster_summary = pd.merge(
        cluster_counts, cluster_numerical_summary, on='cluster_segment'
    )

    return model_df_clustered, cluster_summary

# Execute cached clustering
master_model_df, cluster_summary = run_granular_clustering(master_model_df, optimal_k=8)

# ----------------------------------------------------
# 2. Display Numerical Profiling Table
# ----------------------------------------------------
st.write("**8-Cluster Segment Profiles (Averages per Segment):**")
st.dataframe(cluster_summary, use_container_width=True)

# ----------------------------------------------------
# 3. Categorical Profiling (Safe Dynamic Crosstabs)
# ----------------------------------------------------
with st.expander("🏢 Categorical & Demographic Distributions (%) across 8 Clusters"):
    cat_cols_to_check = ['latest_plan_type', 'industry', 'company_size']
    
    for col in cat_cols_to_check:
        if col in master_model_df.columns:
            st.write(f"**{col.replace('_', ' ').title()} Distribution (%)**")
            breakdown = (
                pd.crosstab(
                    master_model_df['cluster_segment'],
                    master_model_df[col],
                    normalize='index',
                )
                * 100
            ).round(1)
            st.dataframe(breakdown, use_container_width=True)

# ----------------------------------------------------
# 4. Visualizations: Churn Rate & Revenue Contribution
# ----------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))

# Churn Rate Comparison
if 'churn_rate_%' in cluster_summary.columns:
    sns.barplot(
        data=cluster_summary,
        x='cluster_segment',
        y='churn_rate_%',
        hue='cluster_segment',
        legend=False,
        palette='Reds_d',
        ax=ax1,
    )
    ax1.set_title('Churn Rate (%) across 8 Cluster Segments', fontweight='bold')
    ax1.set_xlabel('Cluster Segment')
    ax1.set_ylabel('Churn Rate (%)')
    for p in ax1.patches:
        if p.get_height() > 0:
            ax1.annotate(
                f'{p.get_height():.1f}%',
                (p.get_x() + p.get_width() / 2.0, p.get_height()),
                ha='center', va='bottom',
                xytext=(0, 3), textcoords='offset points',
                fontsize=9, fontweight='bold'
            )

# Average Monthly Revenue Contribution
if 'avg_monthly_revenue' in cluster_summary.columns:
    sns.barplot(
        data=cluster_summary,
        x='cluster_segment',
        y='avg_monthly_revenue',
        hue='cluster_segment',
        legend=False,
        palette='Greens_d',
        ax=ax2,
    )
    ax2.set_title('Avg Monthly Revenue ($) across 8 Cluster Segments', fontweight='bold')
    ax2.set_xlabel('Cluster Segment')
    ax2.set_ylabel('Avg Monthly Revenue ($)')
    for p in ax2.patches:
        if p.get_height() > 0:
            ax2.annotate(
                f'${p.get_height():.2f}',
                (p.get_x() + p.get_width() / 2.0, p.get_height()),
                ha='center', va='bottom',
                xytext=(0, 3), textcoords='offset points',
                fontsize=9, fontweight='bold'
            )

plt.tight_layout()

# Render plot in Streamlit app
st.pyplot(fig)
plt.close(fig)

"""# **Churn Analysis**

**Goal:** To evaluate customer churn timing across a 24-month lifecycle by grouping accounts into tenure cohorts and cross-referencing them against plan types (Basic, Pro, Enterprise) and behavioral engagement signals.

**Key Execution Steps:**

Tenure Cohort Binning (pd.cut): Segments total_months_active into 5 distinct operational windows: 0–3 Mos (Onboarding), 4–6 Mos (Early Adoption), 7–12 Mos (Mid Tenure), 13–18 Mos (Late Tenure), and 19–24 Mos (Mature / Renewal).
Churn Matrix Calculation (groupby & unstack): Computes the exact percentage churn rate (is_churned.mean() * 100) for every combination of tenure cohort and plan type.
Visual Heatmap Generation (sns.heatmap): Renders a color-coded matrix using a red palette (OrRd) to immediately spotlight high-churn risk zones.
Summary Aggregation (agg): Aggregates customer volume (customer_count), overall churn rate (churn_rate_pct), session decay activity (avg_decay_ratio), and monthly revenue (avg_monthly_rev) for each tenure group.

**Key Findings & Business Insights**
1. The Basic Plan "First-Year Cliff" (Highest Risk)
Basic plan subscribers face extreme churn across their entire first year: 39.3% in Months 0–3, peaking at 40.7% in Months 4–6 and 40.8% in Months 7–12.
Compared to Enterprise (26.3%–33.1%) and Pro (30.6%–35.0%), Basic tier users experience severe early value misalignment and onboarding drop-off.
2. The Retention "Safe Zone" (Months 13–18)
Accounts that survive past Month 12 reach the most stable phase of the customer lifecycle, with overall churn dropping to its lowest point at 22.27%.
Basic tier churn plummets from 40.8% (Months 7–12) down to 20.9% (Months 13–18).
3. Behavioral Decay Signals Continuous Drop-off
Activity decay steadily degrades over time: The avg_decay_ratio drops continuously from 0.96 (Months 0–3) down to 0.58 (Months 19–24).
This proves that disengagement begins early—well before actual account cancellation happens.
4. The 2-Year Renewal Spike (Months 19–24)
At the 2-year mark, churn ticks back up across all tiers to 29.83% (Enterprise reaching 31.3%). This highlights a critical contract renewal or platform re-evaluation window.
"""


st.subheader("24-Month Tenure Cohort & Churn Timing Matrix")

# ----------------------------------------------------
# 1. Prepare Tenure Cohort Data (Cached)
# ----------------------------------------------------
@st.cache_data
def analyze_tenure_cohorts(df):
    data = df.copy()

    # Bin total_months_active into strict 24-Month Cohorts
    tenure_bins = [0, 3, 6, 12, 18, 24]
    tenure_labels = [
        '0–3 Mos (Onboarding)',
        '4–6 Mos (Early Adoption)',
        '7–12 Mos (Mid Tenure)',
        '13–18 Mos (Late Tenure)',
        '19–24 Mos (Mature / Renewal)',
    ]

    data['tenure_cohort'] = pd.cut(
        data['total_months_active'],
        bins=tenure_bins,
        labels=tenure_labels,
        include_lowest=True,
    )

    # Build Churn Timing Matrix
    churn_timing_matrix = (
        data.groupby(['tenure_cohort', 'latest_plan_type'], observed=False)[
            'is_churned'
        ]
        .mean()
        .unstack()
        * 100
    )

    # Build Summary Table
    summary_table = data.groupby('tenure_cohort', observed=False).agg(
        customer_count=('customer_id', 'count'),
        churn_rate_pct=('is_churned', lambda x: (x.mean() * 100) if len(x) > 0 else 0.0),
        avg_decay_ratio=('session_duration_decay_ratio', 'mean'),
        avg_monthly_rev=('avg_monthly_revenue', 'mean'),
    ).round(2).reset_index()

    return churn_timing_matrix, summary_table

# Run cached function
churn_timing_matrix, summary_table = analyze_tenure_cohorts(master_model_df)

# ----------------------------------------------------
# 2. Render Heatmap Plot
# ----------------------------------------------------
fig, ax = plt.subplots(figsize=(10, 5))

sns.heatmap(
    churn_timing_matrix,
    annot=True,
    fmt='.1f',
    cmap='OrRd',
    cbar_kws={'label': 'Churn Rate (%)'},
    ax=ax
)

ax.set_title(
    '24-Month Cohort Churn Rate (%) across Plan Types',
    fontsize=13,
    fontweight='bold',
    pad=12
)
ax.set_xlabel('Plan Type', fontsize=11)
ax.set_ylabel('Tenure Cohort', fontsize=11)

plt.tight_layout()

# Render in Streamlit
st.pyplot(fig)
plt.close(fig)

# ----------------------------------------------------
# 3. Summary Table Display
# ----------------------------------------------------
st.write("**24-Month Tenure Cohort Summary**")
st.dataframe(summary_table, use_container_width=True)

