# -*- coding: utf-8 -*-
"""GrowthFlow Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jtmx2_BAWWgR4dKXdAYK_qcGTqaRSwBm
"""

# Data upload and setup

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

@st.cache_data
def load_all_data():
    customers_df = pd.read_csv('gfcustomer_information.csv')
    status_df = pd.read_csv('gfmonthly_status.csv')
    usage_df = pd.read_csv('gfusage_data.csv')
    feedback_df = pd.read_csv('gffeedback_data.csv')
    engagement_df = pd.read_csv('gfengagement_data.csv')
    
    model_df = customers_df.merge(status_df, on='customer_id', how='inner') \
                           .merge(usage_df, on='customer_id', how='inner') \
                           .merge(feedback_df, on='customer_id', how='inner') \
                           .merge(engagement_df, on='customer_id', how='inner')
                           
    return customers_df, status_df, usage_df, feedback_df, engagement_df, model_df

# Unpack everything so 'customers_df', 'status_df', etc. exist for line 41
customers_df, status_df, usage_df, feedback_df, engagement_df, model_df = load_all_data()

# Dataset Overview

dfs = {
    'Customers': customers_df,
    'Status': status_df,
    'Usage': usage_df,
    'Feedback': feedback_df,
    'Engagement': engagement_df
}

# Table Info
for name, df in dfs.items():
    print(f"=== {name} Table has ({df.shape[0]:,} rows, {df.shape[1]} cols) ===")
    print(list(df.columns))
    display(df.info())
    print("-" * 100)
    print()

# Table Preview
for name, df in dfs.items():
    print(f"=== {name} Table ===")
    display(df.head(3))
    print("-" * 50)

"""# Data Cleaning"""

# Convert Date Columns across all tables
customers_df['subscription_date'] = pd.to_datetime(customers_df['subscription_date'])

status_df['activity_month'] = pd.to_datetime(status_df['activity_month'])
usage_df['activity_month'] = pd.to_datetime(usage_df['activity_month'])

feedback_df['feedback_month'] = pd.to_datetime(feedback_df['feedback_month'])
engagement_df['engagement_month'] = pd.to_datetime(engagement_df['engagement_month'])

print("✓ All date columns converted to datetime.")

# Referential Integrity Check
master_ids = set(customers_df['customer_id'])

dfs_to_check = {
    'Status': status_df,
    'Usage': usage_df,
    'Feedback': feedback_df,
    'Engagement': engagement_df
}

print("\n=== ID ALIGNMENT CHECK ===")
for name, df in dfs_to_check.items():
    table_ids = set(df['customer_id'])
    unmatched = table_ids - master_ids
    if len(unmatched) == 0:
        print(f"✓ {name}: All {len(table_ids):,} unique customers exist in master Customers table.")
    else:
        print(f"⚠️ {name}: Found {len(unmatched)} IDs not present in master Customers table.")

# Check for duplicate customer IDs in the primary dimension table
duplicate_query = """
SELECT
    customer_id,
    COUNT(*) AS occurrence_count
FROM gfcustomer_information
GROUP BY customer_id
HAVING COUNT(*) > 1;
"""

duplicates = pd.read_sql_query(duplicate_query, conn)
print(f"Duplicate Customer IDs found: {len(duplicates)}")

# Inspect unique values in categorical columns to catch typos or whitespace
categorical_query = """
SELECT DISTINCT customer_type
FROM gfcustomer_information;
"""

categories = pd.read_sql_query(categorical_query, conn)
display(categories)

"""# EDA

**Numerical Columns Audit**

**Objective**
Scan all the number-based columns across our database tables (such as company size, monthly revenue, session duration, and satisfaction scores) to check for missing values, average numbers, price ranges, and unusual extremes.
This gives us a clear look at the mathematical health and distribution of our numbers before building advanced statistical models.

**Technical Approach**
Found All Number Columns: Programmatically scanned through every table to pull out purely numerical features.
Calculated Key Summary Stats: For every numeric column, we derived:
Completeness: Checked for missing or empty numbers.
Average vs. Middle (Mean vs. Median): Compared the average value to the middle value to see if extreme outliers were pulling the numbers up or down.
Spread & Ranges (Min & Max): Tracked the lowest and highest values to verify boundary conditions.
Skewness: Measured whether the data was evenly spread out or heavily lopsided toward smaller/larger values.
Consolidated Findings: Combined all numeric metrics into a single reference report.

**Key Results & Insights**
100% Data Completeness:
Zero missing values (missing_count = 0) across every numeric feature in all five tables, confirming strong numerical integrity.
Company Size Distribution:
Lopsided Toward Small Businesses: While the average company size is 498 employees, the median is just 41 employees (ranging from 1 to 4,998). A few massive enterprise clients pull the average up, but most customers are smaller operations.
Revenue & Tenure Baseline:
Tenure: Average customer tenure across active monthly records is 7 months (ranging from 0 to 23 months).
Monthly Revenue: Average revenue per monthly record is $205.37 (ranging from $29.00 to $999.00).
Product Usage Trends:
Session Length: Users average 34.75 minutes per session (median: 30 minutes).
Feature Popularity: Core features like CRM (1.08 uses/mo) and Email Campaigns (0.77 uses/mo) see steady usage. Advanced tools like Custom Workflows (0.05 uses/mo) and Advanced Analytics (0.16 uses/mo) have much lower adoption and are used primarily by power users.
Customer Sentiment & Feedback:
Satisfaction: Customers rate us well, with a balanced average Satisfaction Score of 7.20 / 10 (median: 7.00).
NPS Score: Net Promoter Score averages +21.94 (ranging from -33 to +73), showing generally positive customer sentiment.
Campaign Engagement:
Response Rate: Customers respond to campaigns an average of 53% of the time (0.53 rate).

**Business Takeaway**
Our numerical data is clean, complete, and reliable. The metrics confirm that our typical user is a small business (around 40 employees) spending about $200/month and spending 30 minutes per session on core tools like CRM and email. There is a huge opportunity to drive adoption for underutilized advanced tools to help push clients into higher pricing tiers.
"""

# Descriptive stats for numerical columns across all 5 tables

# Get list of all tables in the database
tables_query = "SELECT name FROM sqlite_master WHERE type='table';"
all_tables = pd.read_sql_query(tables_query, conn)['name'].tolist()

num_summaries = []

for table in all_tables:
    df = pd.read_sql_query(f"SELECT * FROM {table};", conn)
    # Select numeric columns only
    numeric_df = df.select_dtypes(include=[np.number])

    for col in numeric_df.columns:
        num_summaries.append({
            'table_name': table,
            'column_name': col,
            'count': numeric_df[col].count(),
            'missing_count': numeric_df[col].isnull().sum(),
            'mean': round(numeric_df[col].mean(), 2),
            'std': round(numeric_df[col].std(), 2),
            'min': round(numeric_df[col].min(), 2),
            'median': round(numeric_df[col].median(), 2),
            'max': round(numeric_df[col].max(), 2),
            'skewness': round(numeric_df[col].skew(), 2)
        })

# Combine into a single consolidated summary DataFrame
df_numerical_summary = pd.DataFrame(num_summaries)

print("=== CONSOLIDATED NUMERICAL COLUMNS BUCKET ===")
display(df_numerical_summary)

"""**Categorical Columns Audit**

**Objective**
Scan all non-numeric text columns across our 5 database tables (like customer type, plan tier, region, and industry) to check for data quality, count unique categories, and find the most common values.
Think of this as a health check on our text data to ensure there are no missing details or weird entries before running deeper analytics.

**Technical Approach**
Found All Text Columns: Automatically searched through every table to pull out text fields (categories, names, dates, and types).
Ran Quality & Frequency Checks: For every column, we checked:
Completeness: Are there any missing or blank values?
Variety (Cardinality): How many unique choices exist (e.g., 3 customer types, 4 regions)?
Most Common Value (Mode): Which single option appears the most, and what percentage of the total does it make up?
Combined into One Master Summary Table: Consolidated all stats into a single report for easy auditing.

**Key Results & Insights**
100% Data Completeness (Zero Missing Data):
There are 0 missing values across every text column in all 5 tables. The data is extremely clean and ready for modeling.
Customer Profile Highlights (5,000 Accounts):
Main Customer Segment: SMBs (Small-to-Medium Businesses) make up 60.24% of our total customer base (3,012 accounts).
Popular Plan: Basic tier is the most common subscription, representing 53.16% of subscribers (2,658 accounts).
Primary Region: North America is our largest geographic market at 39.52% (1,976 accounts).
Industry Breakdown: Retail is the single largest industry at 17.26% (863 accounts), though customers are well-balanced across 6 different sectors.
Activity & Engagement Logs:
Monthly Status (54,021 records): Peak monthly activity occurred in November 2025 (3,873 active records).
Feedback Logs (1,447 records): Product-related issues/feedback was the top category, making up 44.30% of all customer feedback.
Engagement Logs (14,532 records): Interaction logs peaked in December 2025 (1,223 engagement events).

**Business Takeaway**
Our data hygiene is in excellent shape with zero missing values, meaning we don't need to throw out records or fill in blanks. Our core customer identity is clear: we primarily serve North American SMBs on Basic plans, with Product Feedback being the main reason customers reach out to us.
"""

# Descriptive stats for categorical columns across all 5 tables
# Get all table names from database
tables_query = "SELECT name FROM sqlite_master WHERE type='table';"
all_tables = pd.read_sql_query(tables_query, conn)['name'].tolist()

cat_summaries = []

for table in all_tables:
    df = pd.read_sql_query(f"SELECT * FROM {table};", conn)
    # Select non-numeric / string columns
    categorical_df = df.select_dtypes(include=['object', 'category'])

    for col in categorical_df.columns:
        total_rows = len(categorical_df)
        top_val = categorical_df[col].mode()[0] if not categorical_df[col].empty else None
        top_freq = categorical_df[col].value_counts().iloc[0] if not categorical_df[col].empty else 0

        cat_summaries.append({
            'table_name': table,
            'column_name': col,
            'total_rows': total_rows,
            'unique_values': categorical_df[col].nunique(),
            'missing_count': categorical_df[col].isnull().sum(),
            'most_frequent_value': top_val,
            'top_value_count': top_freq,
            'top_value_pct': round((top_freq / total_rows) * 100, 2)
        })

# Display consolidated categorical summary
df_categorical_summary = pd.DataFrame(cat_summaries)
display(df_categorical_summary)

# 1. Fetch start date, end date, and total distinct months in one query
df = pd.read_sql_query("SELECT MIN(activity_month) AS start, MAX(activity_month) AS end, COUNT(DISTINCT activity_month) AS total_months FROM gfmonthly_status;", conn)

# 2. Extract values and calculate years & remaining months
m = int(df['total_months'].iloc[0])
print(f"Timeframe: {df['start'].iloc[0]} to {df['end'].iloc[0]}")
print(f"Duration : {m} months ({m // 12} years, {m % 12} months)")

"""**High-Level Account Churn & Retention Baseline (SQL Query)**
**Objective**
Calculate our overall company-wide churn rate to set a baseline benchmark.
Instead of looking at specific subgroups or monthly trends, this query steps back to look at all 5,000 customers in our database and divides them into two simple groups: customers who stayed active versus customers who canceled up to our snapshot cutoff date (December 1, 2025).
**Technical Approach**
Found Each Customer's Last Active Month: Used a query to find the single most recent month every customer logged activity.
Flagged Active vs. Canceled Accounts:
Active: Customers whose last logged month was December 2025 (the latest month in our data).
Churned: Customers whose last logged month was before December 2025 (meaning they stopped using the product).
Calculated the Overall Retention Ratio: Derived total account counts and calculated the percentage of the overall customer base that churned versus remained active.

**Key Results & Insights**
Total Customer Base: 5,000 total accounts tracked across the dataset lifecycle.
Active Customer Retention: 3,366 active accounts (67.32% retention rate).
Total Customer Attrition: 1,634 churned accounts.
Overall Baseline Churn Rate: 32.68%.

**Business Takeaway**
32.68% is our company-wide benchmark.
This number gives us a clear standard to judge all other business segments against. Any customer tier, region, or plan with a churn rate higher than 32.68% (such as SMBs at 36.6% or Basic plans at 35.3%) represents an above-average risk zone where retention interventions will have the biggest impact.
"""

# Churn Rate
simple_churn_query = """
SELECT
    COUNT(*) AS total_customers,
    SUM(CASE WHEN max_month < '2025-12-01' THEN 1 ELSE 0 END) AS total_churned,
    SUM(CASE WHEN max_month = '2025-12-01' THEN 1 ELSE 0 END) AS total_active,
    ROUND(
        SUM(CASE WHEN max_month < '2025-12-01' THEN 1.0 ELSE 0.0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate_pct
FROM (
    -- Step 1: Find the last recorded month for each customer
    SELECT customer_id, MAX(activity_month) AS max_month
    FROM gfmonthly_status
    GROUP BY customer_id
);
"""

df_simple = pd.read_sql_query(simple_churn_query, conn)
display(df_simple)

"""**Multi-Dimensional Churn & Volume Segmentation**
**Objective**
Evaluate customer distribution and attrition rates across key operational and demographic dimensions—Industry, Region, Customer Type, and Plan Type—to identify structural churn concentrations and risk profiles.
**Technical Approach**
Captured Final Customer Status: Looked at each customer's final recorded month to mark them as either retained or churned.
Calculated Key Group Metrics: For every category, we measured:
Total Customer Volume: The total number of unique customers in that group.
Churn Rate (%): The percentage of customers in that group who canceled.
Built Comparative Visuals: Created a side-by-side dashboard comparing customer volume directly against churn percentages across all four dimensions.

**Key Results & Insights**
Industry Sectors:
Volume: Customer volume is evenly split across industries (~800–830 customers each).
Churn: Education (34.4%) and Finance (34.3%) have the highest churn rates, while E-commerce (30.2%) is the most stable.
Geographic Regions:
Volume: Europe is our largest market (1,322 customers), followed by Asia-Pacific and Latin America.
Churn: Latin America has the highest cancellation rate (35.2%), while North America, Europe, and Asia-Pacific stay lower (31.2%–33.2%).
Company Size (Customer Type):
Volume: Small-to-Medium Businesses (SMBs) make up the majority of our customers.
Churn: Smaller companies leave at much higher rates. SMBs churn at 36.6%, Mid-Market at 28.9%, and Enterprise accounts at just 23.1%.
Plan Tier:
Volume: Pro and Basic plans hold the vast majority of subscribers.
Churn: Basic plans churn highest (35.3%), Pro at 30.5%, and Enterprise plans lowest (28.5%).

**Business Takeaway**
The data shows a clear pattern: Larger customers stay with us longer.
While smaller accounts (SMBs and Basic plans) churn at higher rates (35%–37%), larger clients (Enterprise) are much more sticky (23%–28% churn). We should focus on simplifying onboarding and initial support for SMBs to lower early drop-offs, while continuing to protect our stable, high-value Enterprise accounts.
"""

# Churn rate by Industy, region, cusomer type, plan type, trends in monthly subscription

# Set overall style
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 11})

# ----------------------------------------------------
# 1. Fetch data and determine churn flag per customer
# ----------------------------------------------------
df_status = pd.read_sql_query("SELECT * FROM gfmonthly_status;", conn)
df_status['activity_month'] = pd.to_datetime(df_status['activity_month'])
max_month = df_status['activity_month'].max()

# Last active month per customer
customer_last = df_status.groupby('customer_id')['activity_month'].max().reset_index()
customer_last['is_churned'] = (customer_last['activity_month'] < max_month).astype(int)

# Merge back to customer profile (most recent row per customer)
customer_profile = df_status.sort_values('activity_month').groupby('customer_id').last().reset_index()
customer_profile['is_churned'] = customer_profile['customer_id'].map(
    customer_last.set_index('customer_id')['is_churned']
)

# ----------------------------------------------------
# 2. Helper function to aggregate volume and churn rate
# ----------------------------------------------------
def get_segment_metrics(col, custom_order=None):
    df_grouped = customer_profile.groupby(col).agg(
        total_customers=('customer_id', 'count'),
        churn_rate=('is_churned', lambda x: x.mean() * 100)
    ).reset_index()

    if custom_order:
        df_grouped[col] = pd.Categorical(df_grouped[col], categories=custom_order, ordered=True)
        df_grouped = df_grouped.sort_values(col)
    else:
        df_grouped = df_grouped.sort_values(by='total_customers', ascending=False)

    return df_grouped

# Prepare all segment DataFrames
ind_df = get_segment_metrics('industry')
reg_df = get_segment_metrics('region')
type_df = get_segment_metrics('customer_type', custom_order=['SMB', 'Mid-market', 'Enterprise'])
plan_df = get_segment_metrics('plan_type', custom_order=['Basic', 'Pro', 'Enterprise'])

# ----------------------------------------------------
# 3. Plot 4x2 side-by-side comparison grid
# ----------------------------------------------------
fig, axes = plt.subplots(4, 2, figsize=(16, 18))

# Helper to annotate values on top of bars
def annotate_bars(ax, is_pct=False):
    for p in ax.patches:
        height = p.get_height()
        if height > 0:
            label = f'{height:.1f}%' if is_pct else f'{int(height):,}'
            ax.annotate(label,
                        (p.get_x() + p.get_width() / 2., height),
                        ha='center', va='bottom',
                        fontsize=10, fontweight='bold',
                        xytext=(0, 3), textcoords='offset points')

# Row 1: Industry (Volume vs Churn Rate)
sns.barplot(data=ind_df, x='industry', y='total_customers', hue='industry', legend=False, palette='Blues_r', ax=axes[0, 0])
axes[0, 0].set_title('Total Customers by Industry', fontsize=12, fontweight='bold')
axes[0, 0].set_ylabel('Total Customers')
axes[0, 0].set_ylim(0, ind_df['total_customers'].max() * 1.18)
annotate_bars(axes[0, 0], is_pct=False)

sns.barplot(data=ind_df, x='industry', y='churn_rate', hue='industry', legend=False, palette='Reds_r', ax=axes[0, 1])
axes[0, 1].set_title('Churn Rate (%) by Industry', fontsize=12, fontweight='bold')
axes[0, 1].set_ylabel('Churn Rate (%)')
axes[0, 1].set_ylim(0, ind_df['churn_rate'].max() * 1.18)
annotate_bars(axes[0, 1], is_pct=True)

# Row 2: Region (Volume vs Churn Rate)
sns.barplot(data=reg_df, x='region', y='total_customers', hue='region', legend=False, palette='Greens_r', ax=axes[1, 0])
axes[1, 0].set_title('Total Customers by Region', fontsize=12, fontweight='bold')
axes[1, 0].set_ylabel('Total Customers')
axes[1, 0].set_ylim(0, reg_df['total_customers'].max() * 1.18)
annotate_bars(axes[1, 0], is_pct=False)

sns.barplot(data=reg_df, x='region', y='churn_rate', hue='region', legend=False, palette='Oranges_r', ax=axes[1, 1])
axes[1, 1].set_title('Churn Rate (%) by Region', fontsize=12, fontweight='bold')
axes[1, 1].set_ylabel('Churn Rate (%)')
axes[1, 1].set_ylim(0, reg_df['churn_rate'].max() * 1.18)
annotate_bars(axes[1, 1], is_pct=True)

# Row 3: Customer Type (Volume vs Churn Rate)
sns.barplot(data=type_df, x='customer_type', y='total_customers', hue='customer_type', legend=False, palette='Blues_r', ax=axes[2, 0])
axes[2, 0].set_title('Total Customers by Customer Type', fontsize=12, fontweight='bold')
axes[2, 0].set_ylabel('Total Customers')
axes[2, 0].set_ylim(0, type_df['total_customers'].max() * 1.18)
annotate_bars(axes[2, 0], is_pct=False)

sns.barplot(data=type_df, x='customer_type', y='churn_rate', hue='customer_type', legend=False, palette='Purples_r', ax=axes[2, 1])
axes[2, 1].set_title('Churn Rate (%) by Customer Type', fontsize=12, fontweight='bold')
axes[2, 1].set_ylabel('Churn Rate (%)')
axes[2, 1].set_ylim(0, type_df['churn_rate'].max() * 1.18)
annotate_bars(axes[2, 1], is_pct=True)

# Row 4: Plan Type (Volume vs Churn Rate)
sns.barplot(data=plan_df, x='plan_type', y='total_customers', hue='plan_type', legend=False, palette='Greens_r', ax=axes[3, 0])
axes[3, 0].set_title('Total Customers by Plan Type', fontsize=12, fontweight='bold')
axes[3, 0].set_ylabel('Total Customers')
axes[3, 0].set_ylim(0, plan_df['total_customers'].max() * 1.18)
annotate_bars(axes[3, 0], is_pct=False)

sns.barplot(data=plan_df, x='plan_type', y='churn_rate', hue='plan_type', legend=False, palette='Reds_r', ax=axes[3, 1])
axes[3, 1].set_title('Churn Rate (%) by Plan Type', fontsize=12, fontweight='bold')
axes[3, 1].set_ylabel('Churn Rate (%)')
axes[3, 1].set_ylim(0, plan_df['churn_rate'].max() * 1.18)
annotate_bars(axes[3, 1], is_pct=True)

plt.tight_layout()
plt.show()

"""**Average Revenue Per User (ARPU) & Price Point Distribution by Plan**

**Objective** Assess how much money our business earns on average from each customer across our three subscription tiers: Basic, Pro, and Enterprise.
This helps us understand how our pricing strategy is working, how customer volume is spread out, and how much extra value we gain when a customer upgrades to a higher plan.
**Technical Approach**
Calculated Key Financial Metrics per Plan:
Average Monthly Revenue (ARPU): The typical monthly earnings per customer record.
Median Revenue: The middle price point for each tier.
Price Boundaries: The minimum and maximum price points charged per plan.
Total Monthly Records: The total volume of active monthly subscriptions per plan.
Organized & Formatted: Arranged plans in order (Basic → Pro → Enterprise) and formatted all dollar values ($) clearly.
Visualized Results: Built a bar chart showing average revenue per user (ARPU) side-by-side with exact dollar labels above each bar.

**Key Results & Insights**
Basic Plan (High Volume, Low Price):
Average Revenue (ARPU): $35.40/month (Median: $29.00).
Price Range: $29.00 to $99.00.
Volume Share: 27,855 active monthly records (nearly 50% of all monthly customer activity).
Pro Plan (Balanced Mid-Tier):
Average Revenue (ARPU): $162.00/month (Median: $199.00).
Price Range: $99.00 to $299.00.
Volume Share: 16,315 active monthly records (29.2% of total activity).
Enterprise Plan (High Value Premium Tier):
Average Revenue (ARPU): $757.80/month (Median: $999.00).
Price Range: $299.00 to $999.00.
Volume Share: 9,851 active monthly records (17.7% of total activity).

**Business Takeaway**
Our pricing structure creates a massive revenue jump at each upgrade tier:
Upgrading a customer from Basic to Pro increases average monthly revenue by ~4.6x (from ~$35 to ~$162).
Upgrading a customer from Pro to Enterprise increases average monthly revenue by ~4.7x (from ~$162 to ~$758).
Encouraging Basic and Pro users to upgrade to higher tiers is one of the most powerful levers we have for growing overall revenue.
"""

# Cost per plan

# Set visual style
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 11})

# 1. Fetch monthly status data
df_status = pd.read_sql_query("SELECT * FROM gfmonthly_status;", conn)

# 2. Calculate revenue breakdown per plan type
plan_pricing = df_status.groupby('plan_type').agg(
    avg_monthly_revenue=('monthly_revenue', 'mean'),
    median_monthly_revenue=('monthly_revenue', 'median'),
    min_monthly_revenue=('monthly_revenue', 'min'),
    max_monthly_revenue=('monthly_revenue', 'max'),
    total_active_records=('customer_id', 'count')
).reset_index()

# Enforce logical ordering: Basic -> Pro -> Enterprise
plan_order = ['Basic', 'Pro', 'Enterprise']
plan_pricing['plan_type'] = pd.Categorical(plan_pricing['plan_type'], categories=plan_order, ordered=True)
plan_pricing = plan_pricing.sort_values('plan_type').reset_index(drop=True)

# ----------------------------------------------------
# 3. Print Summary Table
# ----------------------------------------------------
print("=== MONTHLY REVENUE (PRICING) BREAKDOWN BY PLAN TYPE ===")
formatted_pricing = plan_pricing.copy()
for col in ['avg_monthly_revenue', 'median_monthly_revenue', 'min_monthly_revenue', 'max_monthly_revenue']:
    formatted_pricing[col] = formatted_pricing[col].apply(lambda x: f"${x:,.2f}")

display(formatted_pricing)

# ----------------------------------------------------
# 4. Visual Comparison: Average Revenue per Plan Type
# ----------------------------------------------------
plt.figure(figsize=(9, 5))

ax = sns.barplot(
    data=plan_pricing,
    x='plan_type',
    y='avg_monthly_revenue',
    hue='plan_type',
    legend=False,
    palette='Blues_r'
)

# Annotate bars with exact dollar amounts
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(
            f"${height:,.2f}",
            (p.get_x() + p.get_width() / 2., height),
            ha='center', va='bottom',
            fontsize=11, fontweight='bold',
            xytext=(0, 5), textcoords='offset points'
        )

plt.title('Average Monthly Revenue (ARPU) by Plan Type', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Plan Type', fontsize=12, labelpad=10)
plt.ylabel('Average Monthly Revenue ($)', fontsize=12, labelpad=10)
plt.ylim(0, plan_pricing['avg_monthly_revenue'].max() * 1.18)

# Format y-axis ticks as currency
ax.yaxis.set_major_formatter('${x:,.0f}')

plt.tight_layout()
plt.show()

"""# **Monthly Recurring Revenue (MRR) Loss Analysis by Subscription Plan**
**Objective**
Quantify the total financial impact of customer churn by calculating monthly recurring revenue (MRR) loss across subscription tiers (Basic, Pro, and Enterprise), identifying high-value risk exposure and revenue concentration patterns.

**Technical Approach**
Identified Churned Accounts: Looked at each customer's final active record to flag accounts that canceled before the latest month in our dataset.
Grouped by Subscription Tier: Categorized canceled accounts into Basic, Pro, and Enterprise plans.
Calculated the Financial Metrics:
Total churned customers per plan.
Total monthly revenue lost ($).
Average revenue lost per canceled account ($).
Percentage share of total monthly revenue loss (%).
Visualized the Losses: Created an annotated bar chart displaying the exact dollar loss and account counts side-by-side for clear comparison.

**Key Results & Insights**
Total Revenue Lost: $265,876 per month across 1,634 churned accounts.

Enterprise Plan Exposure (Biggest Financial Risk): Accounts for 62.8 percent of total revenue loss ($166,854/month).Represents only 15.1 percent of canceled accounts (246 accounts), but loses an average of $678.27 per account.

Pro Plan Loss: Accounts for 25.6 percent of revenue loss ($67,949/month) across 451 accounts (~$150.66 per account).

Basic Plan Volume: Has the highest number of cancellations (937 accounts / 57.3% of total volume), but only accounts for 11.6 percent of dollar loss ($31,073/month) because of its low monthly price ($33.16 per account).

**Business Takeaway**
Focus retention efforts on Enterprise accounts. Saving just 1 Enterprise customer recovers roughly the same monthly revenue as keeping 20 Basic customers. Dedicated account management and VIP customer support for Enterprise clients will yield the highest ROI on retention spending.
"""

#Total revenue lost due to churn

# Set visual style
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 11})

# ----------------------------------------------------
# 1. Fetch data & identify churned customers
# ----------------------------------------------------
df_status = pd.read_sql_query("SELECT * FROM gfmonthly_status;", conn)
df_status['activity_month'] = pd.to_datetime(df_status['activity_month'])

# Identify the dataset's latest active month
max_month = df_status['activity_month'].max()

# Get each customer's final active record
last_customer_records = (
    df_status.sort_values('activity_month')
    .groupby('customer_id')
    .last()
    .reset_index()
)

# Flag churned accounts (last active month was before max_month)
last_customer_records['is_churned'] = last_customer_records['activity_month'] < max_month

# Filter down to churned accounts only
churned_df = last_customer_records[last_customer_records['is_churned']].copy()

# ----------------------------------------------------
# 2. Aggregate lost revenue by Plan Type
# ----------------------------------------------------
plan_mrr_loss = churned_df.groupby('plan_type').agg(
    churned_customers=('customer_id', 'count'),
    total_lost_mrr=('monthly_revenue', 'sum'),
    avg_lost_mrr=('monthly_revenue', 'mean')
).reset_index()

# Calculate % share of total lost MRR
total_loss_all_plans = plan_mrr_loss['total_lost_mrr'].sum()
plan_mrr_loss['pct_of_total_loss'] = (plan_mrr_loss['total_lost_mrr'] / total_loss_all_plans) * 100

# Enforce logical plan order
plan_order = ['Basic', 'Pro', 'Enterprise']
plan_mrr_loss['plan_type'] = pd.Categorical(plan_mrr_loss['plan_type'], categories=plan_order, ordered=True)
plan_mrr_loss = plan_mrr_loss.sort_values('plan_type').reset_index(drop=True)

# ----------------------------------------------------
# 3. Print Summary DataFrame
# ----------------------------------------------------
print("=== MONTHLY REVENUE (MRR) LOSS BY PLAN TYPE ===")
formatted_table = plan_mrr_loss.copy()
formatted_table['total_lost_mrr'] = formatted_table['total_lost_mrr'].apply(lambda x: f"${x:,.2f}")
formatted_table['avg_lost_mrr'] = formatted_table['avg_lost_mrr'].apply(lambda x: f"${x:,.2f}")
formatted_table['pct_of_total_loss'] = formatted_table['pct_of_total_loss'].apply(lambda x: f"{x:.1f}%")

display(formatted_table)
print(f"\nTotal Monthly Revenue Lost Across All Plans: ${total_loss_all_plans:,.2f}")

# ----------------------------------------------------
# 4. Plot Lost MRR Chart
# ----------------------------------------------------
plt.figure(figsize=(10, 6))

ax = sns.barplot(
    data=plan_mrr_loss,
    x='plan_type',
    y='total_lost_mrr',
    hue='plan_type',
    legend=False,
    palette='Reds_r'
)

# Annotate bars with dollar amounts and customer counts
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        # Match height to plan row to pull customer count
        plan_row = plan_mrr_loss[plan_mrr_loss['total_lost_mrr'] == height].iloc[0]
        label = f"${height:,.0f}\n({int(plan_row['churned_customers'])} accounts)"

        ax.annotate(
            label,
            (p.get_x() + p.get_width() / 2., height),
            ha='center', va='bottom',
            fontsize=10, fontweight='bold',
            xytext=(0, 5), textcoords='offset points'
        )

plt.title('Total Monthly Revenue (MRR) Lost to Churn by Plan Type', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Plan Type', fontsize=12, labelpad=10)
plt.ylabel('Total Lost Revenue ($)', fontsize=12, labelpad=10)
plt.ylim(0, plan_mrr_loss['total_lost_mrr'].max() * 1.22)

# Format y-axis ticks as currency
ax.yaxis.set_major_formatter('${x:,.0f}')

plt.tight_layout()
plt.show()

"""# Data Ingestion

**Multi-Table Data Ingestion & Alignment**
**Objective**
Integrate five disjointed relational database tables (gfcustomer_information, gfmonthly_status, gfusage_data, gffeedback_data, and gfengagement_data) into a single master analytical dataset without losing row history.

**Technical Approach**
Built the Main Timeline: Used the monthly status table (gfmonthly_status) as our primary backbone so every row represents a customer in a specific month.
Standardized Date Names: Renamed different date labels (like feedback_month and engagement_month) to a single standard column: activity_month.
Prevented Duplicate Info: Kept permanent customer details (like region and industry) solely in the customer information table to avoid cluttered, duplicate columns.
Matched Information Accurately: Linked usage, feedback, and engagement records using the customer's ID and the specific month.
Filled in the Gaps: When a customer had no recorded usage or feedback in a given month, we filled those missing activity counts with 0 rather than leaving blank spaces.
**Key Results**
Master Dataset Size: 55,808 total monthly records, structured cleanly over time.
Complete Customer Coverage: All 5,000 unique customers were successfully linked without losing anyone.
Comprehensive Metrics: 25 total attributes capturing customer profiles, monthly product usage, satisfaction scores, and campaign responses side-by-side.

**Business Takeaway**
By combining these isolated tables into a single master view, we now have a complete 360-degree picture of each customer's monthly journey, making it much easier to analyze retention, usage patterns, and churn risks.
"""

# List all tables in your database
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("=== AVAILABLE TABLES IN YOUR DATABASE ===")
print(tables)

# ----------------------------------------------------
# 0. Load Raw Tables from SQLite Connection
# ----------------------------------------------------
df_customers  = pd.read_sql_query("SELECT * FROM gfcustomer_information;", conn)
df_status     = pd.read_sql_query("SELECT * FROM gfmonthly_status;", conn)
df_usage      = pd.read_sql_query("SELECT * FROM gfusage_data;", conn)
df_feedback   = pd.read_sql_query("SELECT * FROM gffeedback_data;", conn)
df_engagement = pd.read_sql_query("SELECT * FROM gfengagement_data;", conn)

# ----------------------------------------------------
# 1. Clean & Standardize Monthly Join Keys
# ----------------------------------------------------
# Align month column names across all datasets to 'activity_month'
df_feedback_clean = df_feedback.rename(columns={'feedback_month': 'activity_month'})
df_engagement_clean = df_engagement.rename(columns={'engagement_month': 'activity_month'})

# Ensure proper datetime format
date_cols = ['subscription_date', 'cohort', 'activity_month']

for df in [df_customers, df_status, df_usage, df_feedback_clean, df_engagement_clean]:
    for col in date_cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col])

# Drop redundant static attributes from df_status to prevent _x / _y duplicate columns
status_core_cols = [
    col for col in df_status.columns
    if col not in ['cohort', 'industry', 'region', 'customer_type', 'plan_type']
]
df_status_clean = df_status[status_core_cols]

# ----------------------------------------------------
# 2. Sequential Left Joins (Building Monthly Analytical Spine)
# ----------------------------------------------------
# Start with gfmonthly_status as the primary time-series backbone
analytical_df = pd.merge(df_status_clean, df_customers, on='customer_id', how='left')

# Join Usage logs on (customer_id, activity_month)
analytical_df = pd.merge(
    analytical_df,
    df_usage,
    on=['customer_id', 'activity_month'],
    how='left',
    suffixes=('', '_usage')
)

# Join Feedback logs on (customer_id, activity_month)
analytical_df = pd.merge(
    analytical_df,
    df_feedback_clean,
    on=['customer_id', 'activity_month'],
    how='left'
)

# Join Engagement logs on (customer_id, activity_month)
analytical_df = pd.merge(
    analytical_df,
    df_engagement_clean,
    on=['customer_id', 'activity_month'],
    how='left'
)

# Drop redundant 'months_since_sub_usage' if generated during join
if 'months_since_sub_usage' in analytical_df.columns:
    analytical_df.drop(columns=['months_since_sub_usage'], inplace=True)

# ----------------------------------------------------
# 3. Impute Missing Values Post-Merge
# ----------------------------------------------------
# Zero-fill event counts for months where customers had no recorded activity
zero_fill_cols = [
    'session_duration', 'feature_crm', 'feature_email_campaigns',
    'feature_analytics', 'feature_automation', 'engagement_count',
    'response_rate', 'avg_response_rate'
]

for col in zero_fill_cols:
    if col in analytical_df.columns:
        analytical_df[col] = analytical_df[col].fillna(0)

# ----------------------------------------------------
# 4. Ingestion Summary & Verification
# ----------------------------------------------------
print("=== INGESTION SUCCESSFUL ===")
print(f"• Master Analytical Dataset Rows : {len(analytical_df):,}")
print(f"• Unique Customers Retained     : {analytical_df['customer_id'].nunique():,}")
print(f"• Total Distinct Features Joined : {len(analytical_df.columns)}")

print("\n--- Feature List ---")
for idx, col in enumerate(analytical_df.columns, 1):
    print(f"{idx:2d}. {col}")

display(analytical_df.head())

"""**Subscription Cohort Definition & Tenure Calculation**
**Objective**
Organize customers into groups based on when they joined and track how long they've stayed Growth Flow.
**Technical Approach**
1. Grouping Customers by "Signup Month" (Cohorts)
What it does: Instead of looking at exact calendar dates (like April 12, 2024), it rounds everyone’s join date to the 1st of that month (April 1, 2024).
Why it matters: This puts all customers who signed up in April 2024 into one group. It lets us compare how the "April Group" behaves compared to the "May Group" over time.
2. Calculating Customer "Tenure" (Months as a Customer)
What it does: It counts how many months have passed between when a customer signed up and each month they used our service.
Month 0: Their very first month with us.
Month 1: Their second month with us.
Month 9: They’ve been with us for 9 months.
Why it matters: This turns calendar dates into an easy timeline so we can answer questions like: "How many customers leave after 3 months?" or "Does customer spending drop off after Month 6?"

**Results Show**
Steady Growth: We are consistently gaining around 200 to 230 new customers every single month.
Best Performing Signup Months: August 2024 was our biggest acquisition month (232 new customers), followed closely by May 2024 (229 new customers).

**The Big Takeaway**
This step prepares our data so we can clearly see customer loyalty and retention trends. By organizing customers by signup month and measuring their tenure step-by-step, we can easily spot when users are most likely to drop off and step in to keep them.
"""

# Cohort Creation and Monthly subscription

# Ensure date columns are in datetime format
analytical_df['activity_month'] = pd.to_datetime(analytical_df['activity_month'])
analytical_df['subscription_date'] = pd.to_datetime(analytical_df['subscription_date'])

# ----------------------------------------------------
# 1. Create Monthly Subscription Cohort
# ----------------------------------------------------
# Option A: Based on official subscription_date (Normalized to 1st of month)
analytical_df['subscription_cohort'] = analytical_df['subscription_date'].dt.to_period('M').dt.to_timestamp()

# Option B: Alternative - Based on customer's first recorded activity month in dataset
first_activity = analytical_df.groupby('customer_id')['activity_month'].transform('min')
analytical_df['first_activity_cohort'] = first_activity

# ----------------------------------------------------
# 2. Calculate Months Since Subscription
# ----------------------------------------------------
# Precise month-difference calculation between activity_month and subscription cohort
analytical_df['months_since_subscription'] = (
    (analytical_df['activity_month'].dt.year - analytical_df['subscription_cohort'].dt.year) * 12 +
    (analytical_df['activity_month'].dt.month - analytical_df['subscription_cohort'].dt.month)
)

# Replace any negative values with 0 (for edge cases where activity occurs in signup month)
analytical_df['months_since_subscription'] = analytical_df['months_since_subscription'].clip(lower=0)

# ----------------------------------------------------
# 3. Verification & Inspection
# ----------------------------------------------------
print("=== COHORT & TENURE CALCULATIONS COMPLETE ===")
print("• Sample Cohorts & Months Since Subscription:")
display(analytical_df[[
    'customer_id',
    'subscription_date',
    'subscription_cohort',
    'activity_month',
    'months_since_subscription'
]].head(10))

# Cohort Size Distribution
print("\n• Customer Count per Subscription Cohort (Top 10):")
cohort_counts = analytical_df.groupby('subscription_cohort')['customer_id'].nunique().reset_index()
cohort_counts.columns = ['Subscription Cohort', 'Unique Customer Count']
print(cohort_counts.head(10).to_string(index=False))

"""**Customer Retention Matrix & Heatmap Analysis**
**Objective**
This code tracks how long different groups of customers stay active over time.
It organizes customers by the month they signed up (their "cohort") and tracks what percentage of each group is still paying and using our service in Month 1, Month 2, Month 3, and beyond.
**Technical Approach**
Group by Signup Month: Groups every customer based on the month they joined (e.g., all January 2024 signups together).
Track Monthly Activity: Checks each month after signup to see if the customer is still active.
Calculate Retention Percentages: Divides active customers in any given month by the starting total for that signup group to calculate the retention rate (100% starting point).
Visualize as a Heatmap: Plots the results in a grid where dark blue represents high retention and lighter shades show where customers begin to leave (churn).

**Key Takeaways**
Strong Initial Onboarding (Month 1):
Near-perfect retention in the first month across almost all cohorts (99%−100%), showing that new customers get immediate value during initial onboarding.
Gradual Early Drop-Off (Months 2–6):
By Month 3, retention drops slightly to around 93%−97%.
By Month 6, retention settles around 85%−91%, showing a predictable, steady decay rather than a sudden drop.
Long-Term Loyalty Base (Months 12+):
After 1 year (Month 12), roughly 70%−81% of customers remain active.
Retention flattens out around the 70%−75% range for mature accounts (Months 13–20), pointing to a stable core group of loyal long-term subscribers.
Tail-End Drop Off (Final Month):
The sharp drop in the final month column (down to 48%−55%) reflects the cutoff point of the dataset rather than a sudden change in customer behavior.

**Business Takeaway**
Our business enjoys strong early customer retention and a solid long-term foundation, keeping over 70% of subscribers active past the one-year mark. Retention efforts should focus on months 6 through 12 to help more customers cross into that loyal, long-term group.
"""

# Cohort Retention Matrix & Heatmap

# Set visual styling
sns.set_theme(style="white")
plt.rcParams.update({'font.size': 10})

# ----------------------------------------------------
# 1. Prepare Data & Ensure Cohort Indexing
# ----------------------------------------------------
# Ensure dates are datetime objects
analytical_df['activity_month'] = pd.to_datetime(analytical_df['activity_month'])
analytical_df['subscription_date'] = pd.to_datetime(analytical_df['subscription_date'])

# Assign Cohort (1st of signup month)
analytical_df['cohort_month'] = analytical_df['subscription_date'].dt.to_period('M').dt.to_timestamp()

# Calculate Cohort Index (0 = Signup Month, 1 = Month 1, etc.)
analytical_df['cohort_index'] = (
    (analytical_df['activity_month'].dt.year - analytical_df['cohort_month'].dt.year) * 12 +
    (analytical_df['activity_month'].dt.month - analytical_df['cohort_month'].dt.month)
)

# Filter out active flags if applicable (ensure we only count active customer-months)
active_df = analytical_df[analytical_df['is_active'] == 1] if 'is_active' in analytical_df.columns else analytical_df

# ----------------------------------------------------
# 2. Build Count Matrix & Calculate Retention Rates (%)
# ----------------------------------------------------
# Pivot to get count of unique active customers per cohort per month index
cohort_counts = active_df.pivot_table(
    index='cohort_month',
    columns='cohort_index',
    values='customer_id',
    aggfunc='nunique'
)

# Extract initial cohort size (Month 0 count)
cohort_sizes = cohort_counts.iloc[:, 0]

# Calculate percentage retention matrix
retention_matrix = cohort_counts.divide(cohort_sizes, axis=0) * 100

# Format index as clean YYYY-MM labels
retention_matrix.index = retention_matrix.index.strftime('%Y-%m')

# ----------------------------------------------------
# 3. Plot Cohort Retention Heatmap
# ----------------------------------------------------
plt.figure(figsize=(14, 8))
plt.title('Monthly Customer Cohort Retention Matrix (%)', fontsize=14, fontweight='bold', pad=15)

ax = sns.heatmap(
    retention_matrix,
    annot=True,
    fmt='.0f',
    cmap='YlGnBu',
    cbar_kws={'label': 'Retention Rate (%)'},
    linewidths=0.5,
    vmin=0,
    vmax=100
)

# Format axis labels
plt.xlabel('Months Since Subscription (Cohort Index)', fontweight='bold', labelpad=10)
plt.ylabel('Subscription Cohort (Signup Month)', fontweight='bold', labelpad=10)
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

# ----------------------------------------------------
# 4. Overall Monthly Retention Rate Summary
# ----------------------------------------------------
print("=== AVERAGE RETENTION RATE BY COHORT INDEX ===")
avg_retention = retention_matrix.mean(axis=0).reset_index()
avg_retention.columns = ['Months Since Signup', 'Avg Retention Rate (%)']
avg_retention['Avg Retention Rate (%)'] = avg_retention['Avg Retention Rate (%)'].round(2)

print(avg_retention.to_string(index=False))

"""# Feature Engineering

Feature Engineering for Customer-Level Model Snapshot Dataset (5,000 Rows)

***Objective:***
Condense monthly activity history (~55,000 rows) into one single master table with exactly 5,000 rows (one row per customer).

***Technical Approach:***
Calculate Total Tenure & Churn Status: Determine each customer's final active month and sets our target variable (is_churned = 1 for canceled accounts, 0 for active accounts).
Pull Static Demographics: Extracts fixed customer details like company size, industry, region, and customer segment.
Aggregates Lifetime Habits: Computes average monthly revenue, typical session lengths, overall feature usage counts (CRM, Email, Analytics, Automation), and latest feedback ratings.
Engineers Early Warning Signals (session_duration_decay_ratio): Compares usage in a customer's last 2 active months against their lifetime average to detect sudden drops in engagement right before they churn.
Handles Missing Ratings: Fills in blank satisfaction/NPS scores with median values for customers who never submitted feedback.

***Result***
Total Dataset Volume: 5,000 unique customer rows
Feature Dimensionality: 19 clean predictor columns capturing demographics, usage averages, sentiment scores, and pre-churn decay metrics.
Target Variable Balance (is_churned):
Churned Accounts (is_churned = 1): 1,634 customers (32.68% of the customer base).
Active Accounts (is_churned = 0): 3,366 customers (67.32% retention rate).
"""

# ----------------------------------------------------
# 1. Determine Global Max Month & Account Status
# ----------------------------------------------------
max_global_month = analytical_df['activity_month'].max()

customer_tenure = (
    analytical_df.groupby('customer_id')
    .agg(
        last_active_month=('activity_month', 'max'),
        total_months_active=('months_since_sub', 'max'),
        first_subscription_date=('subscription_date', 'min'),
    )
    .reset_index()
)

# Target variable: is_churned (1 = canceled prior to global max month, 0 = active)
customer_tenure['is_churned'] = (
    customer_tenure['last_active_month'] < max_global_month
).astype(int)

# ----------------------------------------------------
# 2. Static Profile Features
# ----------------------------------------------------
static_profile_cols = [
    'customer_id',
    'company_size',
    'industry',
    'region',
    'customer_type',
]
df_static_profiles = analytical_df[static_profile_cols].drop_duplicates(
    subset=['customer_id']
)

# ----------------------------------------------------
# 3. Aggregated Lifetime Baseline Metrics
# ----------------------------------------------------
# Pre-calculate composite platform usage per record to eliminate severe multicollinearity
analytical_df['total_platform_uses_record'] = (
    analytical_df['feature_crm']
    + analytical_df['feature_email_campaigns']
    + analytical_df['feature_analytics']
    + analytical_df['feature_automation']
)

lifetime_agg = (
    analytical_df.groupby('customer_id')
    .agg(
        # Revenue & Plan
        latest_plan_type=('plan_type', 'last'),
        avg_monthly_revenue=('monthly_revenue', 'mean'),
        # Product Usage (Aggregated Composite Feature to replace correlated raw features)
        avg_session_duration=('session_duration', 'mean'),
        total_platform_uses=('total_platform_uses_record', 'sum'),
        # Engagement Volume AND Responsiveness Rate
        avg_engagement_count=('engagement_count', 'mean'),  # Outreach Volume
        engagement_rate=('response_rate', 'mean'),  # Customer Responsiveness %
        latest_satisfaction_score=('satisfaction_score', 'last'),
        latest_nps_score=('nps_score', 'last'),
    )
    .reset_index()
)

# Drop intermediate record-level composite column from analytical_df
analytical_df.drop(columns=['total_platform_uses_record'], inplace=True)

# ----------------------------------------------------
# 4. Feature Engineering: Pre-Churn Trend & Decay Signals
# ----------------------------------------------------
sorted_df = analytical_df.sort_values(['customer_id', 'activity_month'])

recent_2mo_metrics = (
    sorted_df.groupby('customer_id')
    .tail(2)
    .groupby('customer_id')
    .agg(
        recent_2mo_avg_session=('session_duration', 'mean'),
        recent_2mo_avg_revenue=('monthly_revenue', 'mean'),
        recent_2mo_engagement_rate=('response_rate', 'mean'),
        recent_2mo_engagement_count=('engagement_count', 'mean'),
    )
    .reset_index()
)

lifetime_agg = pd.merge(lifetime_agg, recent_2mo_metrics, on='customer_id')

# Trend Ratios (Recent 2-Mo Avg / Lifetime Avg)
lifetime_agg['session_duration_decay_ratio'] = (
    lifetime_agg['recent_2mo_avg_session']
    / (lifetime_agg['avg_session_duration'] + 1e-5)
).round(3)

lifetime_agg['revenue_trend_ratio'] = (
    lifetime_agg['recent_2mo_avg_revenue']
    / (lifetime_agg['avg_monthly_revenue'] + 1e-5)
).round(3)

lifetime_agg['engagement_trend_ratio'] = (
    lifetime_agg['recent_2mo_engagement_rate']
    / (lifetime_agg['engagement_rate'] + 1e-5)
).round(3)

lifetime_agg['outreach_volume_trend_ratio'] = (
    lifetime_agg['recent_2mo_engagement_count']
    / (lifetime_agg['avg_engagement_count'] + 1e-5)
).round(3)

# Drop intermediate raw recent averages
lifetime_agg.drop(
    columns=[
        'recent_2mo_avg_session',
        'recent_2mo_avg_revenue',
        'recent_2mo_engagement_rate',
        'recent_2mo_engagement_count',
    ],
    inplace=True,
)

# ----------------------------------------------------
# 5. Master Model Snapshot Assembly
# ----------------------------------------------------
model_df = pd.merge(df_static_profiles, customer_tenure, on='customer_id')
model_df = pd.merge(model_df, lifetime_agg, on='customer_id')

model_df.drop(
    columns=['last_active_month', 'first_subscription_date'], inplace=True
)

# Impute missing sentiment scores with medians
model_df['latest_satisfaction_score'] = model_df[
    'latest_satisfaction_score'
].fillna(model_df['latest_satisfaction_score'].median())
model_df['latest_nps_score'] = model_df['latest_nps_score'].fillna(
    model_df['latest_nps_score'].median()
)

print("=== FINAL MODEL SNAPSHOT TABLE CREATED (Multicollinearity Reduced) ===")
print(f"• Total Customer Rows : {len(model_df):,}")
print(f"• Total Features      : {len(model_df.columns)}")
display(model_df.head())

"""Export Datasets"""

import os

# ----------------------------------------------------
# 1. Define File Export Paths
# ----------------------------------------------------
ingested_filename = 'ingested_analytical_dataset_55k.csv'
model_filename = 'model_snapshot_dataset_5k.csv'

# ----------------------------------------------------
# 2. Save DataFrames to CSV
# ----------------------------------------------------
# index=False ensures Pandas doesn't add an extra unwanted index column
analytical_df.to_csv(ingested_filename, index=False)
model_df.to_csv(model_filename, index=False)

print("=== DATASETS EXPORTED LOCALLY ===")
print(
    f"1. Ingested Dataset  : '{ingested_filename}' ({len(analytical_df):,} rows)"
)
print(f"2. Model Table       : '{model_filename}' ({len(model_df):,} rows)")

from google.colab import files

# Trigger automatic browser download
files.download(ingested_filename)
files.download(model_filename)



"""# **BASELINE MODELLING-Logistic regression and Random Forest**

**Baseline Modelling**
** Technical Approach**
Separated the Target: Took out the customer IDs and separated the answer key (is_churned) from the rest of the customer features.
Prepared the Data for the Model:
Text into Numbers: Converted text categories (like plan type or region) into 0s and 1s so the mathematical model could read them.
Equalized Scale: Scaled all numerical features (like revenue or session duration) to a standardized range so large numbers didn't overpower smaller ones.
Split the Data: Held back 20% of the dataset (1,000 customers) as a secret test set to evaluate the model fairly, using the other 80% (4,000 customers) to train it.
Trained & Evaluated the Model: Built a basic Logistic Regression model on the training data, asked it to predict churn on the 1,000 test customers, and printed out the score report.
** Results**
While the Logistic Regression model has a slightly higher raw accuracy (67.9% vs. 64.8%), it is practically useless for churn detection because it simply predicts that nearly everyone will stay active.
The Random Forest (Balanced) model successfully fixes this issue, boosting Churn Recall from 8.3% to 48.6%—meaning it captures nearly 6x more actual churners.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# ----------------------------------------------------
# 1. Prepare Feature Set (X) and Target (y)
# ----------------------------------------------------
drop_cols = ['customer_id', 'is_churned']
if 'cluster_k2' in model_df.columns:
    drop_cols.append('cluster_k2')

X = model_df.drop(columns=drop_cols).copy()
y = model_df['is_churned']

# Ensure cluster_segment (k=6) is treated as categorical
if 'cluster_segment' in X.columns:
    X['cluster_segment'] = X['cluster_segment'].astype('str')

# Identify numerical and categorical features
num_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols = X.select_dtypes(
    include=['object', 'category', 'string']
).columns.tolist()

# ----------------------------------------------------
# 2. Encode Categoricals & Train-Test Split (80/20)
# ----------------------------------------------------
X_encoded = pd.get_dummies(X, columns=cat_cols, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.20, random_state=42, stratify=y
)

# Standard Scale numerical features for Logistic Regression
scaler = StandardScaler()
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test_scaled[num_cols] = scaler.transform(X_test[num_cols])

# ----------------------------------------------------
# 3. Train Both Models
# ----------------------------------------------------
# Model A: Baseline Logistic Regression
lr_model = LogisticRegression(random_state=42, max_iter=1000)
lr_model.fit(X_train_scaled, y_train)

# Model B: Random Forest (Balanced)
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
)
rf_model.fit(X_train, y_train)

# ----------------------------------------------------
# 4. Generate Predictions & Metrics
# ----------------------------------------------------
# Predictions
lr_pred = lr_model.predict(X_test_scaled)
lr_proba = lr_model.predict_proba(X_test_scaled)[:, 1]

rf_pred = rf_model.predict(X_test)
rf_proba = rf_model.predict_proba(X_test)[:, 1]

# Metric Calculations
comparison_data = {
    'Metric': [
        'Accuracy',
        'Precision (Class 1)',
        'Recall (Class 1)',
        'F1-Score (Class 1)',
        'ROC-AUC',
    ],
    'Logistic Regression (Baseline)': [
        f'{accuracy_score(y_test, lr_pred):.4f}',
        f"{precision_score(y_test, lr_pred, pos_label=1):.4f}",
        f"{recall_score(y_test, lr_pred, pos_label=1):.4f}",
        f"{f1_score(y_test, lr_pred, pos_label=1):.4f}",
        f'{roc_auc_score(y_test, lr_proba):.4f}',
    ],
    'Random Forest (Balanced)': [
        f'{accuracy_score(y_test, rf_pred):.4f}',
        f"{precision_score(y_test, rf_pred, pos_label=1):.4f}",
        f"{recall_score(y_test, rf_pred, pos_label=1):.4f}",
        f"{f1_score(y_test, rf_pred, pos_label=1):.4f}",
        f'{roc_auc_score(y_test, rf_proba):.4f}',
    ],
}

comparison_df = pd.DataFrame(comparison_data)

# ----------------------------------------------------
# 5. Output Results Side-by-Side
# ----------------------------------------------------

print("\n---------------------------------------------------------------------")
print("--- 1. DETAILED REPORT: LOGISTIC REGRESSION (BASELINE) ---")
print("---------------------------------------------------------------------")
print(classification_report(y_test, lr_pred))

print("\n---------------------------------------------------------------------")
print("--- 2. DETAILED REPORT: RANDOM FOREST (BALANCED) ---")
print("---------------------------------------------------------------------")
print(classification_report(y_test, rf_pred))

print("=====================================================================")
print("             SIDE-BY-SIDE MODEL PERFORMANCE COMPARISON               ")
print("=====================================================================\n")
display(comparison_df)

"""# **Customer Segmentation (Kmeans Clustering)**

**Goal**
Evaluate the optimal number of clusters (k) using the Elbow Method (Within-Cluster Sum of Squares - WCSS) and Silhouette Score Analysis to group customers into distinct behavioral personas based on tenure, platform activity, sentiment, and pre-churn trend decay signals.
**Technical Approach**
2.1 Feature Selection & Engineering
Clustering was performed using 11 continuous attributes spanning four core dimensions:Tenure & Spend; Engagement & Product Depth; Sentiment Scores: latest_satisfaction_score; Pre-Churn Trend Ratios
2.2 Feature Scaling & Optimization Loop
Standardization: All 11 continuous features were standardized using StandardScaler (μ=0,σ=1)
Evaluation Sweep: K-Means models were evaluated across k=2 to k=10 using random initialization (n_init=10, random_state = 42).
**Results & Diagnostics**
The optimization evaluation yielded two primary structural peaks:
Plaintext
=== CLUSTER OPTIMIZATION METRICS ===
k =  3 | Silhouette Score: 0.2868 | WCSS: 34,628.95  <-- Global Peak
k =  8 | Silhouette Score: 0.2578 | WCSS: 20,252.16  <-- Granular Peak

**Final Implementation**
Selected Model: k=3 was chosen as the baseline segment feature (cluster_segment) for downstream predictive modeling to maximize cluster stability and mathematical separation without over-segmenting the dataset.
"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


# ----------------------------------------------------
# 1. Prepare Feature Set for Clustering
# ----------------------------------------------------
clustering_features = [
    'avg_session_duration',
    'total_months_active',
    'total_platform_uses',  # Combined composite usage feature
    'avg_engagement_count',
    'engagement_rate',
    'latest_satisfaction_score',
    'latest_nps_score',
    'session_duration_decay_ratio',
    'revenue_trend_ratio',
    'engagement_trend_ratio',
    'outreach_volume_trend_ratio',
]

X_cluster = model_df[clustering_features].copy()

# Scale features to equalize distance metrics
cluster_scaler = StandardScaler()
X_cluster_scaled = cluster_scaler.fit_transform(X_cluster)

# ----------------------------------------------------
# 2. Elbow Method & Silhouette Analysis (k=2 to 10)
# ----------------------------------------------------
k_range = range(2, 11)
wcss = []  # Within-Cluster Sum of Squares (Inertia)
silhouette_scores = []

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_cluster_scaled)

    wcss.append(kmeans.inertia_)
    score = silhouette_score(X_cluster_scaled, kmeans.labels_)
    silhouette_scores.append(score)

# ----------------------------------------------------
# 3. Plot Diagnostics (Elbow Curve & Silhouette Scores)
# ----------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

# Elbow Method Plot
ax1.plot(k_range, wcss, marker='o', linestyle='--', color='b')
ax1.set_title('Elbow Method (WCSS vs. K)')
ax1.set_xlabel('Number of Clusters (k)')
ax1.set_ylabel('Inertia (WCSS)')
ax1.grid(True)

# Silhouette Score Plot
ax2.plot(k_range, silhouette_scores, marker='s', linestyle='--', color='g')
ax2.set_title('Silhouette Score vs. K')
ax2.set_xlabel('Number of Clusters (k)')
ax2.set_ylabel('Silhouette Score')
ax2.grid(True)

plt.tight_layout()
plt.show()

# Print Silhouette Scores Table
print("=== CLUSTER OPTIMIZATION METRICS ===")
for k, score, inertia in zip(k_range, silhouette_scores, wcss):
    print(f"k = {k:2d} | Silhouette Score: {score:.4f} | WCSS: {inertia:,.2f}")

"""### **Segmentation using K=3**

**Overview**
The k=3 K-Means model represents the primary macro-segmentation framework for GrowthFlow.
**Cluster Profiles Breakdown**

*Cluster 0:* High-Value Power Champions
Demographics: Highly concentrated in Large/Enterprise organizations (250+ employees) across Technology, Finance, and Healthcare sectors.
Plan Types: Predominantly Enterprise (45.2%) and Pro (30.0%) plans; 24.8% Basic.
Usage Behavior: Highest platform adoption (90.52 aggregate platform uses) and longest average session length (56.28 minutes). Strong outreach responsiveness (0.44).
Retention: Highest tenure (15.97 average active months) with stable behavioral decay ratios (≥1.0).
Revenue Contribution: Highest financial density at $505.69 average monthly revenue per account (16.8% of customer base).

*Cluster 1:* Core SMB / Entry Base
Demographics: Concentrated in Micro and Small businesses (1–10 employees) spanning varied SMB verticals.
Plan Types: Dominated by Basic plans (61.6%), followed by Pro (28.5%) and Enterprise (9.9%).
Usage Behavior: Lower platform activity (18.30 total platform uses) and shorter average session lengths (24.35 minutes).
Retention: Lower tenure (8.46 average active months) with higher exposure to early-stage onboarding drop-off.
Revenue Contribution: Lowest spend density at $109.47 average monthly revenue per account, but represents the majority cohort (64.5% of customer base).

*Cluster 2:* Mid-Market Growth & Transition
Demographics: Primary concentration in Mid-Sized organizations (11–250 employees).
Plan Types: Balanced plan distribution across Basic (49.7%), Pro (32.9%), and Enterprise (17.5%).
Usage Behavior: Steady product adoption (25.89 aggregate platform uses, 31.41-minute sessions) with high engagement responsiveness (0.42).
Retention: Moderate tenure (8.91 average active months).
Revenue Contribution: Moderate spend density at $201.61 average monthly revenue per account (18.7% of customer base).

**Strategic Business Recommendations**
Cluster 0: Assign dedicated Account Executives to secure multi-year annual renewals and protect top-tier revenue.
Cluster 1: Deploy automated, self-serve onboarding guides in Weeks 1–4 to reduce early account drop-off.
Cluster 2: Target accounts with feature enablement playbooks and incentives to drive Pro and Enterprise plan upgrades
"""

# ----------------------------------------------------
# 1. Fit Final K-Means Model (k = 3)
# ----------------------------------------------------
optimal_k = 3

clustering_features = [
    'avg_session_duration',
    'total_months_active',
    'total_platform_uses',  # Updated composite usage feature
    'avg_engagement_count',
    'engagement_rate',
    'latest_satisfaction_score',
    'latest_nps_score',
    'session_duration_decay_ratio',
    'revenue_trend_ratio',
    'engagement_trend_ratio',
    'outreach_volume_trend_ratio',
]

# Scale feature set
cluster_scaler = StandardScaler()
X_cluster_scaled = cluster_scaler.fit_transform(model_df[clustering_features])

# Train K-Means & assign cluster labels
kmeans_3 = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
model_df['cluster_segment'] = kmeans_3.fit_predict(X_cluster_scaled)

print(
    f'=== K-MEANS CLUSTERING COMPLETED ({optimal_k} Segments Assigned) ==='
)
print(model_df['cluster_segment'].value_counts().sort_index())

# ----------------------------------------------------
# 2. Numerical Profiling: Behavioral, Usage, Revenue & Retention Metrics
# ----------------------------------------------------
profile_metrics = [
    'total_months_active',  # Tenure
    'avg_monthly_revenue',  # Revenue Contribution
    'is_churned',  # Churn Rate
    'avg_session_duration',  # Usage Depth
    'total_platform_uses',  # Composite Platform Usage
    'avg_engagement_count',  # Outreach Volume
    'engagement_rate',  # Customer Responsiveness
    'latest_satisfaction_score',
    'latest_nps_score',
    'session_duration_decay_ratio',  # Activity Trend
    'revenue_trend_ratio',
]

cluster_numerical_summary = (
    model_df.groupby('cluster_segment')[profile_metrics]
    .mean()
    .round(2)
    .reset_index()
)

# Convert churn mean to percentage
cluster_numerical_summary['churn_rate_%'] = (
    cluster_numerical_summary['is_churned'] * 100
).round(1)

# Add customer count per segment
cluster_counts = (
    model_df['cluster_segment'].value_counts().sort_index().reset_index()
)
cluster_counts.columns = ['cluster_segment', 'customer_count']
cluster_summary = pd.merge(
    cluster_counts, cluster_numerical_summary, on='cluster_segment'
)

# ----------------------------------------------------
# 3. Categorical Profiling: Demographics & Plan Types
# ----------------------------------------------------
plan_breakdown = (
    pd.crosstab(
        model_df['cluster_segment'],
        model_df['latest_plan_type'],
        normalize='index',
    )
    * 100
).round(1)
industry_breakdown = (
    pd.crosstab(
        model_df['cluster_segment'],
        model_df['industry'],
        normalize='index',
    )
    * 100
).round(1)
company_size_breakdown = (
    pd.crosstab(
        model_df['cluster_segment'],
        model_df['company_size'],
        normalize='index',
    )
    * 100
).round(1)

# Display Summaries
print('\n--- 1. Numerical & Behavioral Profile Table ---')
display(cluster_summary.style.background_gradient(cmap='Blues'))

print('\n--- 2. Plan Type Distribution (%) Per Cluster ---')
display(plan_breakdown)

# ----------------------------------------------------
# 4. Visualizations: Churn Rate & Revenue Contribution by Segment
# ----------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))

# Churn Rate Comparison
sns.barplot(
    data=cluster_summary,
    x='cluster_segment',
    y='churn_rate_%',
    palette='Reds_d',
    ax=ax1,
)
ax1.set_title('Churn Rate (%) by Customer Cluster Segment', fontsize=12)
ax1.set_xlabel('Cluster Segment')
ax1.set_ylabel('Churn Rate (%)')
for p in ax1.patches:
    ax1.annotate(
        f'{p.get_height():.1f}%',
        (p.get_x() + p.get_width() / 2.0, p.get_height()),
        ha='center',
        va='bottom',
        xytext=(0, 3),
        textcoords='offset points',
    )

# Average Monthly Revenue Contribution
sns.barplot(
    data=cluster_summary,
    x='cluster_segment',
    y='avg_monthly_revenue',
    palette='Greens_d',
    ax=ax2,
)
ax2.set_title('Average Monthly Revenue ($) by Cluster Segment', fontsize=12)
ax2.set_xlabel('Cluster Segment')
ax2.set_ylabel('Avg Monthly Revenue ($)')
for p in ax2.patches:
    ax2.annotate(
        f'${p.get_height():.2f}',
        (p.get_x() + p.get_width() / 2.0, p.get_height()),
        ha='center',
        va='bottom',
        xytext=(0, 3),
        textcoords='offset points',
    )

plt.tight_layout()
plt.show()

"""
# **Segmentation using k=8**

Cluster 0: "The Struggling Onboarders"
Cluster 1: "The Fading Veterans"
Cluster 2: "The Enterprise Champions"
Cluster 3: "The Steady SMB Backbone"
Cluster 4: "The Silent Subscribers"
Cluster 5: "The Mid-Market Powerhouses"
Cluster 6: "The Engaged Newcomers"
Cluster 7: "The Mid-Tier Regulars"

**To reduce Churn we need to Focus On: **

**Cluster 0 :** "The Struggling On boarders"
Brand-new accounts (active for under 3 months) who barely use the platform.
The Danger: 37pct Churn Rate. They get stuck early and cancel almost immediately.
Fix: Send automated "Getting Started" guides and offer live onboarding help in Week 1.

**Cluster 1 :** "The Fading Veterans"- Older accounts (~12 months active) on low spend who have stopped logging in. The Danger: 38pct Churn Rate (Highest). They have slowly outgrown or forgotten the tool.
Fix: Trigger automated re-engagement emails asking if they need help or new features.

**Cluster 6 :** "The Engaged Newcomers"
Newer accounts (~4 months active) who respond heavily to your outreach emails and check-ins. 32pct Churn Rate
The Status: High engagement, growing fast.
Fix: Keep feeding them training materials to make sure they turn into long-term Champions (Cluster 2).

🎯 Main Takeaway for Leadership
The single biggest insight from k=8 is that churn happens for two totally different reasons:
Early Friction (Cluster 0): Customers leaving in Month 1–3 because they can't figure out the software.
Late Decay (Cluster 1): Customers leaving in Month 12 because they slowly stopped using it.

"""

# ----------------------------------------------------
# 1. Fit Final K-Means Model (k = 8)
# ----------------------------------------------------
optimal_k = 8

clustering_features = [
    'avg_session_duration',
    'total_months_active',
    'total_platform_uses',  # Updated composite usage feature
    'avg_engagement_count',
    'engagement_rate',
    'latest_satisfaction_score',
    'latest_nps_score',
    'session_duration_decay_ratio',
    'revenue_trend_ratio',
    'engagement_trend_ratio',
    'outreach_volume_trend_ratio',
]

# Scale feature set
cluster_scaler = StandardScaler()
X_cluster_scaled = cluster_scaler.fit_transform(model_df[clustering_features])

# Train K-Means & assign cluster labels
kmeans_8 = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
model_df['cluster_segment'] = kmeans_8.fit_predict(X_cluster_scaled)

print(
    f'=== K-MEANS CLUSTERING COMPLETED ({optimal_k} Segments Assigned) ==='
)
print(model_df['cluster_segment'].value_counts().sort_index())

# ----------------------------------------------------
# 2. Numerical Profiling: Behavioral, Usage, Revenue & Retention Metrics
# ----------------------------------------------------
profile_metrics = [
    'total_months_active',  # Tenure
    'avg_monthly_revenue',  # Revenue Contribution
    'is_churned',  # Churn Rate
    'avg_session_duration',  # Usage Depth
    'total_platform_uses',  # Composite Platform Usage
    'avg_engagement_count',  # Outreach Volume
    'engagement_rate',  # Customer Responsiveness
    'latest_satisfaction_score',
    'latest_nps_score',
    'session_duration_decay_ratio',  # Activity Trend
    'revenue_trend_ratio',
]

cluster_numerical_summary = (
    model_df.groupby('cluster_segment')[profile_metrics]
    .mean()
    .round(2)
    .reset_index()
)

# Convert churn mean to percentage
cluster_numerical_summary['churn_rate_%'] = (
    cluster_numerical_summary['is_churned'] * 100
).round(1)

# Add customer count per segment
cluster_counts = (
    model_df['cluster_segment'].value_counts().sort_index().reset_index()
)
cluster_counts.columns = ['cluster_segment', 'customer_count']
cluster_summary = pd.merge(
    cluster_counts, cluster_numerical_summary, on='cluster_segment'
)

# ----------------------------------------------------
# 3. Categorical Profiling: Demographics & Plan Types
# ----------------------------------------------------
plan_breakdown = (
    pd.crosstab(
        model_df['cluster_segment'],
        model_df['latest_plan_type'],
        normalize='index',
    )
    * 100
).round(1)
industry_breakdown = (
    pd.crosstab(
        model_df['cluster_segment'],
        model_df['industry'],
        normalize='index',
    )
    * 100
).round(1)
company_size_breakdown = (
    pd.crosstab(
        model_df['cluster_segment'],
        model_df['company_size'],
        normalize='index',
    )
    * 100
).round(1)

# Display Summaries
print('\n--- 1. Numerical & Behavioral Profile Table ---')
display(cluster_summary.style.background_gradient(cmap='Blues'))

print('\n--- 2. Plan Type Distribution (%) Per Cluster ---')
display(plan_breakdown)

# ----------------------------------------------------
# 4. Visualizations: Churn Rate & Revenue Contribution by Segment
# ----------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))

# Churn Rate Comparison
sns.barplot(
    data=cluster_summary,
    x='cluster_segment',
    y='churn_rate_%',
    palette='Reds_d',
    ax=ax1,
)
ax1.set_title('Churn Rate (%) by Customer Cluster Segment', fontsize=12)
ax1.set_xlabel('Cluster Segment')
ax1.set_ylabel('Churn Rate (%)')
for p in ax1.patches:
    ax1.annotate(
        f'{p.get_height():.1f}%',
        (p.get_x() + p.get_width() / 2.0, p.get_height()),
        ha='center',
        va='bottom',
        xytext=(0, 3),
        textcoords='offset points',
    )

# Average Monthly Revenue Contribution
sns.barplot(
    data=cluster_summary,
    x='cluster_segment',
    y='avg_monthly_revenue',
    palette='Greens_d',
    ax=ax2,
)
ax2.set_title('Average Monthly Revenue ($) by Cluster Segment', fontsize=12)
ax2.set_xlabel('Cluster Segment')
ax2.set_ylabel('Avg Monthly Revenue ($)')
for p in ax2.patches:
    ax2.annotate(
        f'${p.get_height():.2f}',
        (p.get_x() + p.get_width() / 2.0, p.get_height()),
        ha='center',
        va='bottom',
        xytext=(0, 3),
        textcoords='offset points',
    )

plt.tight_layout()
plt.show()

"""# **Churn Analysis**

**Goal:** To evaluate customer churn timing across a 24-month lifecycle by grouping accounts into tenure cohorts and cross-referencing them against plan types (Basic, Pro, Enterprise) and behavioral engagement signals.

**Key Execution Steps:**

Tenure Cohort Binning (pd.cut): Segments total_months_active into 5 distinct operational windows: 0–3 Mos (Onboarding), 4–6 Mos (Early Adoption), 7–12 Mos (Mid Tenure), 13–18 Mos (Late Tenure), and 19–24 Mos (Mature / Renewal).
Churn Matrix Calculation (groupby & unstack): Computes the exact percentage churn rate (is_churned.mean() * 100) for every combination of tenure cohort and plan type.
Visual Heatmap Generation (sns.heatmap): Renders a color-coded matrix using a red palette (OrRd) to immediately spotlight high-churn risk zones.
Summary Aggregation (agg): Aggregates customer volume (customer_count), overall churn rate (churn_rate_pct), session decay activity (avg_decay_ratio), and monthly revenue (avg_monthly_rev) for each tenure group.

**Key Findings & Business Insights**
1. The Basic Plan "First-Year Cliff" (Highest Risk)
Basic plan subscribers face extreme churn across their entire first year: 39.3% in Months 0–3, peaking at 40.7% in Months 4–6 and 40.8% in Months 7–12.
Compared to Enterprise (26.3%–33.1%) and Pro (30.6%–35.0%), Basic tier users experience severe early value misalignment and onboarding drop-off.
2. The Retention "Safe Zone" (Months 13–18)
Accounts that survive past Month 12 reach the most stable phase of the customer lifecycle, with overall churn dropping to its lowest point at 22.27%.
Basic tier churn plummets from 40.8% (Months 7–12) down to 20.9% (Months 13–18).
3. Behavioral Decay Signals Continuous Drop-off
Activity decay steadily degrades over time: The avg_decay_ratio drops continuously from 0.96 (Months 0–3) down to 0.58 (Months 19–24).
This proves that disengagement begins early—well before actual account cancellation happens.
4. The 2-Year Renewal Spike (Months 19–24)
At the 2-year mark, churn ticks back up across all tiers to 29.83% (Enterprise reaching 31.3%). This highlights a critical contract renewal or platform re-evaluation window.
"""

data = model_df.copy()

# 1. Bin total_months_active into strict 24-Month Cohorts
tenure_bins = [0, 3, 6, 12, 18, 24]
tenure_labels = [
    '0–3 Mos (Onboarding)',
    '4–6 Mos (Early Adoption)',
    '7–12 Mos (Mid Tenure)',
    '13–18 Mos (Late Tenure)',
    '19–24 Mos (Mature / Renewal)',
]

data['tenure_cohort'] = pd.cut(
    data['total_months_active'],
    bins=tenure_bins,
    labels=tenure_labels,
    include_lowest=True,
)

# 2. Build Churn Timing Matrix
churn_timing_matrix = (
    data.groupby(['tenure_cohort', 'latest_plan_type'], observed=False)[
        'is_churned'
    ]
    .mean()
    .unstack()
    * 100
)

# 3. Plot Churn Rate Heatmap
plt.figure(figsize=(10, 5))
sns.heatmap(
    churn_timing_matrix,
    annot=True,
    fmt='.1f',
    cmap='OrRd',
    cbar_kws={'label': 'Churn Rate (%)'},
)
plt.title(
    '24-Month Cohort Churn Rate (%) across Plan Types',
    fontsize=13,
    fontweight='bold',
)
plt.xlabel('Plan Type', fontsize=11)
plt.ylabel('Tenure Cohort', fontsize=11)
plt.tight_layout()
plt.show()

# 4. Display Summary Table
summary_table = data.groupby('tenure_cohort', observed=False).agg(
    customer_count=('customer_id', 'count'),
    churn_rate_pct=('is_churned', lambda x: x.mean() * 100),
    avg_decay_ratio=('session_duration_decay_ratio', 'mean'),
    avg_monthly_rev=('avg_monthly_revenue', 'mean'),
)

print('--- 24-MONTH TENURE COHORT SUMMARY ---')
display(summary_table.round(2))

"""### **Interactive Dashboard**"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import plotly.graph_objects as go
# 
# st.set_page_config(layout="wide", page_title="GrowthFlow Analytics")
# 
# st.title("GrowthFlow Executive Analytics Dashboard")
# st.markdown("Cohort Retention, Segmentation, Churn Timing & Revenue Insights")
# 
# # 1. Load Data
# @st.cache_data
# def load_data():
#     try:
#         return pd.read_csv("model_df.csv")
#     except:
#         return model_df.copy()
# 
# df_dash = load_data()
# 
# tenure_bins = [0, 3, 6, 12, 18, 24]
# tenure_labels = ['0–3 Mos', '4–6 Mos', '7–12 Mos', '13–18 Mos', '19–24 Mos']
# df_dash['tenure_cohort'] = pd.cut(
#     df_dash['total_months_active'],
#     bins=tenure_bins,
#     labels=tenure_labels,
#     include_lowest=True,
# )
# 
# # 2. Key Metrics
# col1, col2, col3, col4 = st.columns(4)
# col1.metric("Total Customers", f"{len(df_dash):,}")
# col2.metric("Overall Churn Rate", f"{df_dash['is_churned'].mean()*100:.1f}%" if len(df_dash) > 0 else "0%")
# col3.metric("Avg Monthly Revenue", f"${df_dash['avg_monthly_revenue'].mean():.2f}" if len(df_dash) > 0 else "$0")
# col4.metric("Avg Decay Ratio", f"{df_dash['session_duration_decay_ratio'].mean():.2f}" if len(df_dash) > 0 else "0")
# 
# st.divider()
# 
# # 3. Charts Row 1
# c1, c2 = st.columns(2)
# 
# with c1:
#     st.subheader("Cohort Retention Heatmap (%)")
#     matrix = df_dash.groupby(['tenure_cohort', 'latest_plan_type'], observed=False)['is_churned'].mean().unstack() * 100
#     retention_matrix = 100 - matrix
#     fig_heatmap = px.imshow(retention_matrix, text_auto='.1f', color_continuous_scale='Blues')
#     st.plotly_chart(fig_heatmap, use_container_width=True)
# 
# with c2:
#     st.subheader("Monthly Revenue Density by Cohort")
#     rev_df = df_dash.groupby(['tenure_cohort', 'latest_plan_type'], observed=False)['avg_monthly_revenue'].mean().reset_index()
#     fig_rev = px.bar(rev_df, x='tenure_cohort', y='avg_monthly_revenue', color='latest_plan_type', barmode='group')
#     st.plotly_chart(fig_rev, use_container_width=True)
# 
# # 4. Charts Row 2
# c3, c4 = st.columns(2)
# 
# with c3:
#     st.subheader("Customer Distribution")
#     fig_sunburst = px.sunburst(df_dash, path=['industry', 'latest_plan_type'], values='avg_monthly_revenue', color='latest_plan_type')
#     st.plotly_chart(fig_sunburst, use_container_width=True)
# 
# with c4:
#     st.subheader("Activity Decay Trajectory")
#     decay_df = df_dash.groupby('tenure_cohort', observed=False)['session_duration_decay_ratio'].mean().reset_index()
#     fig_decay = px.line(decay_df, x='tenure_cohort', y='session_duration_decay_ratio', markers=True)
#     st.plotly_chart(fig_decay, use_container_width=True)

model_df.to_csv('model_df.csv', index=False)

